import type { DrawingSheet } from '../housePlans/drawingPackage';
import type { Opening, Wall } from '../../types';

/** Where a DXF layer belongs in a multi-sheet drawing set. */
export type CadLayerKind = 'floor' | 'elevation' | 'foundation' | 'annotation' | 'other';

/** How a segment is used for plate overlay / extrusion. */
export type CadSegmentRole = 'wall' | 'opening' | 'fixture' | 'soft' | 'elevation' | 'other';

export type CadLayerInfo = {
  name: string;
  kind: CadLayerKind;
  role: CadSegmentRole;
  visible: boolean;
  segmentCount: number;
};

export type CadSegmentFt = {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  layer: string;
  role: CadSegmentRole;
  linetype?: string;
};

export type CadOpeningHintFt = {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  kind: 'door' | 'window' | 'passage' | 'garage';
  layer?: string;
  /** Window sill height above finished floor (feet). Doors/passages/garages use 0. */
  sillFt?: number;
  /** Host wall index when placed on a wall centerline. */
  hostWallIndex?: number;
  /** Parameter along host wall [0..1]. */
  hostT?: number;
  /** Opening clear width (feet). */
  widthFt?: number;
  /** Schedule mark e.g. D1 / W2. */
  mark?: string;
};

export type CadWallCenterlineFt = {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  layer?: string;
  exterior?: boolean;
  /** Wall thickness in feet (defaults: exterior 0.59 ≈ 7", interior 0.39 ≈ 4.7"). */
  thicknessFt?: number;
  /** Paint / finish preset id (stucco, paint, brick, stone, wood). */
  materialId?: CadWallMaterialId;
  /** Multi-building membership (default = primary building). */
  buildingId?: string;
};

export type CadWallMaterialId = 'stucco' | 'paint' | 'brick' | 'stone' | 'wood' | 'interior';

/** Straight run stair on the CAD plate (Plan7-inspired). */
export type CadStairFt = {
  id: string;
  /** Bottom-left of run in plan feet (toward first step). */
  xFt: number;
  yFt: number;
  /** Horizontal run length (feet). */
  runFt: number;
  /** Stair width (feet). */
  widthFt: number;
  /** Total rise (feet). */
  riseFt: number;
  steps: number;
  /** Rotation degrees (0 = run along +X). */
  rotationDeg: number;
  railing?: boolean;
  layer: string;
};

export type CadLabelFt = {
  x: number;
  y: number;
  text: string;
  layer?: string;
};

/** Construction guide line (non-built; snap target). */
export type CadGuidelineFt = {
  id: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
};

/** Architectural roof style for procedural massing (Plan7-inspired). */
export type CadRoofKind = 'auto' | 'gable' | 'flat' | 'shed';

/** User roof overrides on the CAD plate (catalog / inspector). */
export type CadRoofOverrides = {
  kind: CadRoofKind;
  /** Rise inches per 12" run (e.g. 6 = 6/12). Ignored for flat. */
  pitchRise12: number;
  overhangFt: number;
  ridgeAlongX?: boolean;
  /** Prefer procedural roof over DXF elevation profile. */
  forceProcedural?: boolean;
};

/** Raw fixture pose from DXF INSERT / CIRCLE (plan feet after plate build). */
export type CadFixtureKind = 'counter' | 'island' | 'sink' | 'toilet' | 'tub' | 'appliance' | 'other';

export type CadFixtureHintFt = {
  xFt: number;
  yFt: number;
  widthFt?: number;
  depthFt?: number;
  radiusFt?: number;
  rotationDeg?: number;
  layer: string;
  blockName?: string;
  kind?: CadFixtureKind;
};

/** Procedural 3D fixture instance for Extrude view (plan feet). */
export type CadFixtureInstance = {
  id: string;
  kind: CadFixtureKind;
  xFt: number;
  yFt: number;
  widthFt: number;
  depthFt: number;
  heightM: number;
  rotationRad: number;
  layer?: string;
  blockName?: string;
};

export type CadBoundsFt = {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
};

/** Site / outdoor plate (Plan7-style terrace, driveway, garden, balcony, foundation, plot). */
export type CadSlabKind = 'terrace' | 'driveway' | 'garden' | 'balcony' | 'footing' | 'foundation' | 'plot';

export type CadSlabFt = {
  id: string;
  kind: CadSlabKind;
  /** Closed polygon in plan feet (first ≠ last; closed on render). */
  points: Array<{ x: number; y: number }>;
  /** Vertical thickness in feet. */
  thicknessFt: number;
  /** Bottom of slab relative to finished floor (feet). */
  elevationFt: number;
  layer: string;
  /** Auto perimeter railing (balcony default on). */
  railing?: boolean;
  /** True when generated by Auto foundation (safe to clear/rebuild). */
  auto?: boolean;
};

/** Auto foundation under exterior walls (Plan7 Fundament-inspired). */
export type CadFoundationOverrides = {
  enabled: boolean;
  mode: 'slab' | 'footing' | 'slab+footing';
  /** Outward offset from exterior contour (feet). */
  offsetFt: number;
  slabThicknessFt: number;
  footingWidthFt: number;
  footingDepthFt: number;
};

/** Gable dormer seated on the roof (plan feet). */
export type CadDormerFt = {
  id: string;
  /** Center of dormer face on plan. */
  xFt: number;
  yFt: number;
  widthFt: number;
  depthFt: number;
  /** Height of dormer walls above eave (feet). */
  heightFt: number;
  /** Face rotation degrees (0 = faces +Y). */
  rotationDeg: number;
  pitchRise12: number;
  layer: string;
  buildingId?: string;
};

/** Plan section cut line (looking toward the right when walking start→end). */
export type CadSectionCutFt = {
  id: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  /** Half-depth of cutting plane (feet) for 3D clip. */
  depthFt: number;
  label: string;
  layer: string;
};

/** Named building on a multi-building plate. */
export type CadBuilding = {
  id: string;
  name: string;
  /** Optional plan offset for satellite buildings (feet). */
  offsetXFt: number;
  offsetYFt: number;
  visible: boolean;
};

/** Approx site terrain (Plan7 Gelände-inspired heightfield). */
export type CadTerrainOverrides = {
  enabled: boolean;
  /** Rise over run as percent grade (e.g. 4 = 4%). */
  gradePercent: number;
  /** Direction of uphill (degrees; 0 = +X). */
  directionDeg: number;
  /** Grid extent padding beyond plate bounds (feet). */
  padFt: number;
};

/** Title block metadata for sheet-set export. */
export type CadTitleBlock = {
  projectName: string;
  sheetTitle: string;
  drawnBy: string;
  checkedBy: string;
  scaleLabel: string;
  dateLabel: string;
  revision: string;
  address?: string;
};

/** Elevation sheet segment — X = width from left, Y = height above grade (feet). */
export type CadElevationSegmentFt = {
  x1Ft: number;
  y1Ft: number;
  x2Ft: number;
  y2Ft: number;
  layer: string;
  role: CadSegmentRole;
  linetype?: string;
};

export type CadElevationFace = 'front' | 'side' | 'rear';

export type CadElevationSheet = {
  face: CadElevationFace;
  name: string;
  segments: CadElevationSegmentFt[];
  bounds: CadBoundsFt;
  labels: CadLabelFt[];
  gradeFt: number;
};

export type CadPlanFace = 'south' | 'north' | 'east' | 'west';

export type CadRoofProfilePoint = { xFt: number; yFt: number };

export type CadRoofMassing = {
  style: 'procedural' | 'dxf';
  /** Architectural kind used by procedural mesh (flat/gable/shed). */
  kind: 'gable' | 'flat' | 'shed';
  ridgeHeightM: number;
  /** True when the ridge runs parallel to plan X (side-elevation / eave faces front). */
  ridgeAlongX: boolean;
  /** Ridge envelope from ROOF linework on the front elevation (DXF mode). */
  profile?: CadRoofProfilePoint[];
  overhangM: number;
  facadeWidthFt: number;
  facadeDepthFt: number;
  /** Pitch as rise/12 when procedural. */
  pitchRise12?: number;
};

export type CadMassing = {
  frontFace: CadPlanFace;
  storyHeightM: number;
  roof: CadRoofMassing;
  frontElevation?: CadElevationSheet;
  sideElevation?: CadElevationSheet;
  facadeWidthFt: number;
  facadeDepthFt: number;
  /** Elevation sheet height (grade to ridge) in feet. */
  facadeHeightFt: number;
  /** Plan bounds (feet) for aligning facade plane to walls. */
  planBounds: CadBoundsFt;
};

/**
 * CAD plate — source of truth for the CAD-first studio.
 * Rooms are not required; walls extrude from wall-layer centerlines.
 */
export type CadPlate = {
  id: string;
  sourceFileName: string;
  importedAt: string;
  warnings: string[];
  layers: CadLayerInfo[];
  /** Exact DXF linework in feet (plan Y flipped to match sheet/PDF orientation). */
  segments: CadSegmentFt[];
  wallCenterlines: CadWallCenterlineFt[];
  openingHints: CadOpeningHintFt[];
  /** Room names and similar plan labels (feet, same frame as segments). */
  labels: CadLabelFt[];
  /** INSERT/CIRCLE poses for procedural Extrude meshes. */
  fixtureHints: CadFixtureHintFt[];
  /** Site slabs (terrace, driveway, garden, balcony) in plan feet. */
  slabs: CadSlabFt[];
  /** Straight stairs (plan feet). */
  stairs: CadStairFt[];
  /** Construction guidelines (snap aids; not extruded). */
  guidelines?: CadGuidelineFt[];
  /** Roof catalog overrides (null/undefined = auto from DXF elevation or procedural gable). */
  roof?: CadRoofOverrides;
  /** Auto foundation under exterior walls. */
  foundation?: CadFoundationOverrides;
  /** Roof dormers. */
  dormers?: CadDormerFt[];
  /** Plan section cut lines. */
  sectionCuts?: CadSectionCutFt[];
  /** Named buildings (primary + satellites). */
  buildings?: CadBuilding[];
  /** Site terrain approx. */
  terrain?: CadTerrainOverrides;
  /** Title block defaults for sheet-set export. */
  titleBlock?: CadTitleBlock;
  /** Front elevation linework (width × height ft) when DXF has elevation viewports. */
  elevationFront?: CadElevationSheet;
  /** Side/rear elevation linework when available. */
  elevationSide?: CadElevationSheet;
  sheets: DrawingSheet[];
  bounds: CadBoundsFt;
  sheetSource: 'dxf_viewport' | 'pdf' | 'static' | 'mixed' | 'synthetic';
  pdfUrl?: string;
};

/** Computed 2D building section from a cut line. */
export type CadSectionHit = {
  stationFt: number;
  thicknessFt: number;
  heightFt: number;
  exterior: boolean;
  openings: Array<{ sillFt: number; headFt: number; widthFt: number }>;
};

export type CadSectionDrawing = {
  cut: CadSectionCutFt;
  lengthFt: number;
  storyHeightFt: number;
  ridgeHeightFt: number;
  hits: CadSectionHit[];
  gradeFt: number;
};

export type CadExtrusion = {
  walls: Wall[];
  openings: Opening[];
  fixtures: CadFixtureInstance[];
  slabs: CadSlabFt[];
  stairs: CadStairFt[];
  centerFt: { cx: number; cy: number };
  heightM: number;
  massing: CadMassing;
  /** Plan-feet centerlines used for corner miter trims in 3D. */
  wallSegmentsFt: Array<{ x1: number; y1: number; x2: number; y2: number; exterior?: boolean }>;
};
