import {ExternalLink,Search,X} from 'lucide-react';
import {memo,useMemo,useState,type CSSProperties} from 'react';
import {usePlannerStore} from '../../store/plannerStore';
import {catalog} from './catalogData';
import type {RoomType} from '../../types';
import {useInventoryStore} from '../../store/inventoryStore';

const categories=['All','Appliances','Cabinetry','Surfaces','Tile','Plumbing','Paneling','Seating','Tables','Storage','Bedroom','Lighting','Decor'];
const roomCategories:Record<RoomType,string[]>={
 'Bedroom':['Bedroom','Storage','Lighting','Decor'],'Living room':['Seating','Tables','Storage','Lighting','Decor','Paneling'],'Bathroom':['Plumbing','Cabinetry','Tile','Surfaces','Lighting'],'Kitchen':['Appliances','Cabinetry','Surfaces','Plumbing','Tile','Lighting'],'Dining room':['Seating','Tables','Storage','Lighting','Decor'],'Office':['Tables','Seating','Storage','Lighting','Decor'],'Children’s room':['Bedroom','Storage','Lighting','Decor'],'Laundry':['Appliances','Cabinetry','Storage','Surfaces','Plumbing','Lighting'],'Hallway':['Storage','Lighting','Decor'],'Storage / wardrobe':['Storage','Cabinetry','Lighting','Decor'],'Outdoor':['Seating','Tables','Lighting','Decor','Surfaces']
};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});

export const CatalogPanel=memo(function CatalogPanel({close,onAdd,roomType}:{close:()=>void;onAdd?:()=>void;roomType:RoomType}){
 const add=usePlannerStore(s=>s.addFurniture),custom=useInventoryStore(s=>s.items),[q,setQ]=useState(''),[category,setCategory]=useState('All'),[vendor,setVendor]=useState('All'),[sort,setSort]=useState('name'),[recommended,setRecommended]=useState(true),relevant=roomCategories[roomType],all=useMemo(()=>[...catalog,...custom],[custom]),vendors=useMemo(()=>['All',...Array.from(new Set(all.map(i=>i.brand).filter(Boolean) as string[])).sort()],[all]);
 const visibleCategories=recommended?['All',...Array.from(new Set([...relevant,...custom.filter(i=>i.roomTypes?.includes(roomType)).map(i=>i.category)]))]:['All',...Array.from(new Set([...categories,...all.map(i=>i.category)]))];
 const items=useMemo(()=>all.filter(i=>{const haystack=`${i.brand??''} ${i.model??''} ${i.sku??''} ${i.name} ${i.category} ${i.tags?.join(' ')??''}`.toLowerCase(),roomMatch=i.roomTypes?.length?i.roomTypes.includes(roomType):relevant.includes(i.category);return(!recommended||roomMatch)&&(category==='All'||i.category===category)&&(vendor==='All'||i.brand===vendor)&&haystack.includes(q.toLowerCase())}).sort((a,b)=>sort==='price-low'?(a.price??Infinity)-(b.price??Infinity):sort==='price-high'?(b.price??-1)-(a.price??-1):a.name.localeCompare(b.name)),[all,q,category,vendor,sort,recommended,relevant,roomType]);
 return <aside className="catalog-panel"><div className="catalog-title"><div><p className="eyebrow">OLSEN-SOURCED PRODUCTS</p><h2>{roomType} products</h2></div><button aria-label="Close catalog" onClick={close}><X size={18}/></button></div><label className="room-filter"><input type="checkbox" checked={recommended} onChange={e=>{setRecommended(e.target.checked);setCategory('All')}}/>Recommended for this room</label><p className="catalog-disclaimer">Manufacturer MSRP and dimensions are references only—not an Olsen installed-price quote.</p><div className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, SKU, or brands"/></div><div className="catalog-selects"><select aria-label="Filter by vendor" value={vendor} onChange={e=>setVendor(e.target.value)}>{vendors.map(v=><option key={v}>{v}</option>)}</select><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></div><div className="catalog-result-count">{items.length} products</div><div className="chips">{visibleCategories.map(c=><button className={c===category?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="catalog-grid">{items.map(i=><article key={i.id} draggable onDragStart={e=>e.dataTransfer.setData('catalogId',i.id)}><div className="thumb" style={{'--product-color':i.color} as CSSProperties}>{i.thumbnailUrl?<img src={i.thumbnailUrl} loading="lazy" alt=""/>:i.emoji}</div>{i.brand&&<span className="catalog-brand">{i.brand}</span>}<strong>{i.name}</strong>{i.sku&&<small>SKU {i.sku}</small>}<span>{i.price!==undefined?`${money.format(i.price)} / ${i.priceUnit??'each'}`:'Price by dealer/design'}</span>{i.placeholderOnly&&<small>Dimensionally accurate placeholder</small>}{i.note&&<small>{i.note}</small>}{i.sourceUrl&&<a href={i.sourceUrl} target="_blank" rel="noreferrer" draggable={false}>{i.sourceLabel} <ExternalLink size={10}/></a>}<button onClick={()=>{add(i.id,i.name,i.category,i.dims,i.color);onAdd?.()}}><span className="desktop-add-label">Add to room</span><span className="mobile-add-label">Add &amp; view in 3D</span></button></article>)}</div></aside>
});
