import {useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,Upload,X} from 'lucide-react';
import * as XLSX from 'xlsx';
import type {CatalogItem,PriceUnit} from './catalogData';
import {useInventoryStore} from '../../store/inventoryStore';

type Raw=Record<string,unknown>;
type Parsed={row:number;item?:CatalogItem;errors:string[]};
const aliases:Record<string,string>={vendor:'vendor_name',brand:'vendor_name',product:'product_name',name:'product_name',room_type:'room_types',rooms:'room_types',sub_category:'subcategory',unit_price:'price',unit:'price_unit',width_in:'width',depth_in:'depth',height_in:'height',image_url:'thumbnail_url',glb_url:'model_url'};
const key=(value:string)=>aliases[value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')]??value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const text=(v:unknown)=>v===undefined||v===null?'':String(v).trim();
const num=(v:unknown)=>{const n=Number(String(v??'').replace(/[$,%]/g,''));return Number.isFinite(n)?n:undefined};
const yes=(v:unknown)=>['true','yes','y','1'].includes(text(v).toLowerCase());
const list=(v:unknown)=>text(v).split(/[|,;]/).map(x=>x.trim()).filter(Boolean);
const meters=(value:unknown,unit:string)=>{const n=num(value);if(n===undefined)return undefined;switch(unit.toLowerCase()){case'in':case'inch':case'inches':return n*.0254;case'ft':case'feet':return n*.3048;case'cm':return n/100;case'mm':return n/1000;default:return n}};
const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

function parseRow(source:Raw,index:number):Parsed{const row=Object.fromEntries(Object.entries(source).map(([k,v])=>[key(k),v])),errors:string[]=[],vendor=text(row.vendor_name),sku=text(row.sku),name=text(row.product_name),category=text(row.category),unit=text(row.dimension_unit)||'m',width=meters(row.width,unit),depth=meters(row.depth,unit),height=meters(row.height,unit);if(!vendor)errors.push('vendor_name is required');if(!sku)errors.push('sku is required');if(!name)errors.push('product_name is required');if(!category)errors.push('category is required');if(!width||!depth||!height)errors.push('positive width, depth, and height are required');const price=num(row.price),vendorId=text(row.vendor_id)||slug(vendor),id=`${slug(vendorId)}-${slug(sku)}`;if(errors.length)return{row:index+2,errors};const item:CatalogItem={id,sku,vendorId,name,brand:vendor,model:text(row.manufacturer)||text(row.variant_name)||undefined,category,subcategory:text(row.subcategory)||undefined,roomTypes:list(row.room_types),tags:list(row.tags),dims:[width!,depth!,height!],color:text(row.color)||'#b9b9b2',price,msrp:num(row.msrp),cost:num(row.cost),laborCost:num(row.labor_cost),currency:text(row.currency)||'USD',priceUnit:(text(row.price_unit)||'each') as PriceUnit,priceVerifiedAt:text(row.price_last_verified_at)||undefined,sellable:row.sellable===''?true:yes(row.sellable),placeholderOnly:yes(row.placeholder_only)||!text(row.model_url),mountingType:text(row.mounting_type)||'floor',placementSurfaces:list(row.placement_surfaces),finish:text(row.finish)||undefined,material:text(row.material)||undefined,variantGroup:text(row.variant_group)||undefined,variantName:text(row.variant_name)||undefined,availability:text(row.availability)||text(row.stock_status)||undefined,leadTimeDays:num(row.lead_time_days),thumbnailUrl:text(row.thumbnail_url)||undefined,modelUrl:text(row.model_url)||undefined,lowPolyModelUrl:text(row.low_poly_model_url)||undefined,emoji:'▧',sourceUrl:text(row.vendor_product_url)||text(row.vendor_website)||undefined,sourceLabel:`${vendor} product page`,note:price===undefined?'Vendor price required':`Imported vendor price · ${text(row.price_unit)||'each'}`};return{row:index+2,item,errors}}

export function InventoryImportDialog({close}:{close:()=>void}){const upsert=useInventoryStore(s=>s.upsert),existing=useInventoryStore(s=>s.items),lastImportAt=useInventoryStore(s=>s.lastImportAt),[fileName,setFileName]=useState(''),[parsed,setParsed]=useState<Parsed[]>([]),[mode,setMode]=useState<'create-update'|'create-only'|'replace-vendor'>('create-update'),[message,setMessage]=useState('');const valid=useMemo(()=>parsed.flatMap(r=>r.item?[r.item]:[]),[parsed]),errors=parsed.filter(r=>r.errors.length),duplicates=useMemo(()=>{const seen=new Set<string>(),dupes=new Set<string>();for(const item of valid){const k=`${item.vendorId}|${item.sku}`;seen.has(k)?dupes.add(k):seen.add(k)}return dupes},[valid]);
 const choose=async(file:File)=>{setMessage('');setFileName(file.name);try{let rows:Raw[];if(file.name.toLowerCase().endsWith('.json')){const json=JSON.parse(await file.text());rows=Array.isArray(json)?json:Array.isArray(json.items)?json.items:[]}else{const bytes=await file.arrayBuffer(),workbook=XLSX.read(bytes,{type:'array',cellDates:true}),sheet=workbook.Sheets[workbook.SheetNames[0]];rows=XLSX.utils.sheet_to_json<Raw>(sheet,{defval:''})}const results=rows.map(parseRow);const seen=new Set<string>();for(const result of results){if(!result.item)continue;const id=`${result.item.vendorId}|${result.item.sku}`;if(seen.has(id)){result.errors.push('duplicate vendor + SKU in file');delete result.item}else seen.add(id)}setParsed(results);if(!rows.length)setMessage('The file contains no inventory rows.')}catch(e){setParsed([]);setMessage(e instanceof Error?e.message:'The file could not be read.')}};
 const commit=()=>{if(!valid.length)return;const result=upsert(valid,mode);setMessage(`Import complete: ${result.created} created, ${result.updated} updated, ${result.skipped} skipped.`)};
 const downloadErrors=()=>{const csv=['row,errors',...errors.map(e=>`${e.row},"${e.errors.join('; ').replaceAll('"','""')}"`)].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='roomcraft-inventory-errors.csv';a.click();URL.revokeObjectURL(a.href)};
 return <div className="inventory-dialog-backdrop" role="presentation"><section className="inventory-dialog" role="dialog" aria-modal="true" aria-labelledby="inventory-title"><header><div><p className="eyebrow">CATALOG ADMINISTRATION</p><h2 id="inventory-title">Import vendor inventory</h2></div><button onClick={close} aria-label="Close inventory import"><X/></button></header><div className="inventory-actions"><a href="/vendor-inventory-template.xlsx" download><Download/>Blank XLSX template</a><a href="/vendor-inventory-example.xlsx" download><FileSpreadsheet/>Example XLSX</a></div><label className="inventory-drop"><Upload/><strong>Choose XLSX, CSV, or JSON</strong><span>Rows are validated locally before anything is imported.</span><input type="file" accept=".xlsx,.xls,.csv,.json" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></label>{fileName&&<div className="inventory-summary"><strong>{fileName}</strong><span>{valid.length} valid · {errors.length} errors · {existing.length} already imported</span></div>}<label>Import mode<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="create-update">Create new and update matches</option><option value="create-only">Create new; skip matches</option><option value="replace-vendor">Replace each vendor in this file</option></select></label>{duplicates.size>0&&<p className="inventory-warning"><AlertTriangle/>Duplicate vendor/SKU combinations must be corrected.</p>}{parsed.length>0&&<div className="inventory-preview"><table><thead><tr><th>Row</th><th>Vendor / SKU</th><th>Product</th><th>Category</th><th>Price</th><th>Status</th></tr></thead><tbody>{parsed.slice(0,50).map(r=><tr key={r.row} className={r.errors.length?'invalid':''}><td>{r.row}</td><td>{r.item?.brand??'—'}<small>{r.item?.sku}</small></td><td>{r.item?.name??'Invalid row'}</td><td>{r.item?.category??'—'}</td><td>{r.item?.price===undefined?'Quote':`${r.item.currency} ${r.item.price}`}</td><td>{r.errors.length?<span title={r.errors.join('; ')}><AlertTriangle/> {r.errors.join('; ')}</span>:<span><CheckCircle2/> Ready</span>}</td></tr>)}</tbody></table>{parsed.length>50&&<small>Showing the first 50 of {parsed.length} rows.</small>}</div>}{errors.length>0&&<button className="inventory-error-download" onClick={downloadErrors}>Download {errors.length} row errors</button>}{message&&<p className="inventory-message" role="status">{message}</p>}<footer><span>{lastImportAt?`Last import ${new Date(lastImportAt).toLocaleString()}`:'No vendor file imported yet'}</span><button onClick={commit} disabled={!valid.length||duplicates.size>0}>Import {valid.length} products</button></footer></section></div>}
