/**
 * Room flooring finishes — apply via floor-fill (tap product, then tap a room).
 * PBR albedo (+ optional roughness/normal) under /public/catalog/floors/pbr.
 */
export const residentialFlooring = [
  {
    id: 'floor-oak-hardwood',
    name: 'White Oak Hardwood',
    category: 'Flooring',
    subcategory: 'Hardwood',
    dims: [0.127, 0.019, 1.219],
    color: '#c9a57a',
    price: 8.5,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'White oak',
    finish: 'Natural matte',
    textureUrl: '/catalog/floors/pbr/oak-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/oak-rough.jpg',
    normalMapUrl: '/catalog/floors/pbr/oak-normal.jpg',
    textureRepeat: 1.4,
    roughness: 0.72,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'hardwood', 'wood'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Dining room',
      'Office',
      'Hallway',
      'Children’s room',
      'Kitchen',
    ],
    note: '5×48 in 3D planks · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-walnut-hardwood',
    name: 'Walnut Hardwood',
    category: 'Flooring',
    subcategory: 'Hardwood',
    dims: [0.127, 0.019, 1.219],
    color: '#6b4a32',
    price: 11,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Walnut',
    finish: 'Satin',
    textureUrl: '/catalog/floors/pbr/walnut-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/walnut-rough.jpg',
    normalMapUrl: '/catalog/floors/pbr/walnut-normal.jpg',
    textureRepeat: 1.5,
    roughness: 0.65,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'hardwood', 'wood'],
    roomTypes: ['Bedroom', 'Living room', 'Dining room', 'Office', 'Hallway'],
    note: 'Wide-plank 3D walnut boards · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-ash-laminate',
    name: 'Ash Laminate Plank',
    category: 'Flooring',
    subcategory: 'Laminate',
    dims: [0.19, 0.008, 1.38],
    color: '#d7cfc3',
    price: 3.25,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Laminate',
    finish: 'Wood-look',
    textureUrl: '/catalog/floors/pbr/ash-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/ash-rough.jpg',
    normalMapUrl: '/catalog/floors/pbr/ash-normal.jpg',
    textureRepeat: 1.35,
    roughness: 0.7,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'laminate'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Dining room',
      'Office',
      'Hallway',
      'Children’s room',
      'Kitchen',
      'Laundry',
    ],
    note: 'Click-lock 3D laminate planks · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-vinyl-gray',
    name: 'Gray Luxury Vinyl Plank',
    category: 'Flooring',
    subcategory: 'Vinyl',
    dims: [0.178, 0.005, 1.219],
    color: '#8f9194',
    price: 4.75,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'LVP',
    finish: 'Waterproof',
    textureUrl: '/catalog/floors/pbr/vinyl-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/vinyl-rough.jpg',
    textureRepeat: 1.3,
    roughness: 0.78,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'vinyl', 'lvp'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Kitchen',
      'Bathroom',
      'Laundry',
      'Hallway',
      'Children’s room',
      'Office',
    ],
    note: 'Waterproof 3D LVP planks · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-concrete-polished',
    name: 'Polished Concrete',
    category: 'Flooring',
    subcategory: 'Concrete',
    dims: [1, 0.1, 1],
    color: '#9b9b98',
    price: 6.5,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Concrete',
    finish: 'Polished',
    textureUrl: '/catalog/floors/pbr/concrete-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/concrete-rough.jpg',
    textureRepeat: 2.2,
    roughness: 0.45,
    thumbnailUrl: '/catalog/thumbs/floor-concrete.svg',
    tags: ['flooring', 'concrete'],
    roomTypes: ['Living room', 'Kitchen', 'Laundry', 'Hallway', 'Outdoor'],
    note: 'Sealed polished slab look · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-ceramic-white',
    name: 'White Ceramic Floor Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.305, 0.01, 0.305],
    color: '#e8e6e1',
    price: 4.5,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Ceramic',
    finish: 'Matte',
    textureUrl: '/catalog/floors/pbr/ceramic-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/ceramic-rough.jpg',
    textureRepeat: 0.6,
    roughness: 0.55,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'ceramic'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry', 'Hallway'],
    note: '12×12 in 3D ceramic tiles · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-porcelain-gray',
    name: 'Gray Porcelain Plank Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.3048, 0.01, 0.6096],
    color: '#9aa0a6',
    price: 5.75,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Porcelain',
    finish: 'Rectified',
    textureUrl: '/catalog/floors/pbr/porcelain-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/porcelain-rough.jpg',
    normalMapUrl: '/catalog/floors/pbr/porcelain-normal.jpg',
    textureRepeat: 0.75,
    roughness: 0.5,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'porcelain'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry', 'Hallway', 'Living room'],
    note: '12×24 in 3D porcelain tiles · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-hex-stone',
    name: 'Hexagon Stone Mosaic',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.305, 0.01, 0.305],
    color: '#c2b7a6',
    price: 9.25,
    priceUnit: 'sq ft' as const,
    emoji: '⬡',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Natural stone look',
    finish: 'Honed',
    textureUrl: '/catalog/floors/pbr/stone-tile-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/stone-tile-rough.jpg',
    normalMapUrl: '/catalog/floors/pbr/stone-tile-normal.jpg',
    textureRepeat: 0.85,
    roughness: 0.8,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'mosaic'],
    roomTypes: ['Bathroom', 'Kitchen', 'Hallway', 'Laundry'],
    note: '3D hex mosaic field · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-subway-tile',
    name: 'Subway Ceramic Floor Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.152, 0.01, 0.076],
    color: '#f7f5f1',
    price: 3.9,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Ceramic',
    finish: 'Gloss',
    textureUrl: '/catalog/floors/pbr/ceramic-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/ceramic-rough.jpg',
    textureRepeat: 0.4,
    roughness: 0.4,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'subway'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry'],
    note: '3×6 in 3D subway tiles, running bond · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-carpet-beige',
    name: 'Beige Loop Carpet',
    category: 'Flooring',
    subcategory: 'Carpet',
    dims: [3.66, 0.012, 3.66],
    color: '#c4aa88',
    price: 3.8,
    priceUnit: 'sq ft' as const,
    emoji: '▭',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Nylon loop',
    finish: 'Soft',
    textureUrl: '/catalog/floors/pbr/carpet-color.jpg',
    roughnessMapUrl: '/catalog/floors/pbr/carpet-rough.jpg',
    textureRepeat: 1.6,
    roughness: 1,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'carpet'],
    roomTypes: ['Bedroom', 'Living room', 'Office', 'Children’s room', 'Hallway'],
    note: 'Broadloom carpet look · tap then tap a room to fill the floor',
  },
];
