/**
 * Dimensionally realistic residential furnishings for room planning.
 * dims = [width, depth, height] in meters (US common sizes converted from inches).
 * Colored proxies — no proprietary brand models.
 */
export const residentialFurniture = [
  // ── Bedroom ──────────────────────────────────────────────────────────
  {
    id: 'twin-platform-bed',
    name: 'Twin Platform Bed',
    category: 'Bedroom',
    subcategory: 'Beds',
    dims: [1.07, 2.11, 0.9],
    color: '#cbb8a0',
    price: 449,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/bed.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    material: 'Wood / upholstery',
    tags: ['bed', 'twin', 'sleep'],
    roomTypes: ['Bedroom', 'Children’s room'],
    note: 'Twin frame ≈ 42×83×35 in (mattress 38×75 in)',
  },
  {
    id: 'full-platform-bed',
    name: 'Full Platform Bed',
    category: 'Bedroom',
    subcategory: 'Beds',
    dims: [1.45, 2.11, 0.95],
    color: '#c4b09a',
    price: 649,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/bed.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bed', 'full', 'sleep'],
    roomTypes: ['Bedroom', 'Children’s room'],
    note: 'Full frame ≈ 57×83×37 in (mattress 54×75 in)',
  },
  {
    id: 'king-platform-bed',
    name: 'King Platform Bed',
    category: 'Bedroom',
    subcategory: 'Beds',
    dims: [2.03, 2.16, 1.05],
    color: '#d0c2b0',
    price: 1199,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/bed.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bed', 'king', 'sleep'],
    roomTypes: ['Bedroom'],
    note: 'King frame ≈ 80×85×41 in (mattress 76×80 in)',
  },
  {
    id: 'cal-king-platform-bed',
    name: 'California King Platform Bed',
    category: 'Bedroom',
    subcategory: 'Beds',
    dims: [1.93, 2.24, 1.05],
    color: '#cfc0ad',
    price: 1249,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/bed.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bed', 'california-king', 'sleep'],
    roomTypes: ['Bedroom'],
    note: 'Cal King frame ≈ 76×88×41 in (mattress 72×84 in)',
  },
  {
    id: 'nightstand-drawer',
    name: 'Two-Drawer Nightstand',
    category: 'Bedroom',
    subcategory: 'Nightstands',
    dims: [0.51, 0.41, 0.61],
    color: '#8a6f52',
    price: 189,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/nightstand.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['nightstand', 'bedroom'],
    roomTypes: ['Bedroom', 'Children’s room'],
    note: '≈ 20×16×24 in',
  },
  {
    id: 'bedroom-bench',
    name: 'Upholstered Bed Bench',
    category: 'Bedroom',
    subcategory: 'Benches',
    dims: [1.37, 0.46, 0.48],
    color: '#a89888',
    price: 279,
    emoji: '▬',
    thumbnailUrl: '/catalog/thumbs/bed.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bench', 'bedroom'],
    roomTypes: ['Bedroom'],
    note: '≈ 54×18×19 in — foot-of-bed seating',
  },

  // ── Seating ──────────────────────────────────────────────────────────
  {
    id: 'sofa-three-seat',
    name: 'Three-Seat Sofa',
    category: 'Seating',
    subcategory: 'Sofas',
    dims: [2.18, 0.97, 0.86],
    color: '#9a958c',
    price: 1499,
    emoji: '🛋️',
    thumbnailUrl: '/catalog/thumbs/sofa.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['sofa', 'living'],
    roomTypes: ['Living room'],
    note: '≈ 86×38×34 in',
  },
  {
    id: 'loveseat',
    name: 'Loveseat',
    category: 'Seating',
    subcategory: 'Sofas',
    dims: [1.55, 0.94, 0.86],
    color: '#8f8a82',
    price: 999,
    emoji: '🛋️',
    thumbnailUrl: '/catalog/thumbs/sofa.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['loveseat', 'sofa'],
    roomTypes: ['Living room', 'Office'],
    note: '≈ 61×37×34 in',
  },
  {
    id: 'sectional-chaise',
    name: 'Sectional with Chaise',
    category: 'Seating',
    subcategory: 'Sofas',
    dims: [2.74, 1.73, 0.86],
    color: '#8c867c',
    price: 2199,
    emoji: '🛋️',
    thumbnailUrl: '/catalog/thumbs/sofa.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['sectional', 'sofa', 'chaise'],
    roomTypes: ['Living room'],
    note: '≈ 108×68×34 in overall footprint',
  },
  {
    id: 'accent-lounge-chair',
    name: 'Accent Lounge Chair',
    category: 'Seating',
    subcategory: 'Chairs',
    dims: [0.79, 0.86, 0.84],
    color: '#7a5c45',
    price: 549,
    emoji: '🪑',
    thumbnailUrl: '/catalog/thumbs/chair.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['chair', 'lounge', 'accent'],
    roomTypes: ['Living room', 'Bedroom', 'Office'],
    note: '≈ 31×34×33 in',
  },
  {
    id: 'dining-side-chair',
    name: 'Dining Side Chair',
    category: 'Seating',
    subcategory: 'Chairs',
    dims: [0.48, 0.56, 0.91],
    color: '#a87850',
    price: 149,
    emoji: '🪑',
    thumbnailUrl: '/catalog/thumbs/chair.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['chair', 'dining'],
    roomTypes: ['Dining room', 'Kitchen', 'Living room'],
    note: '≈ 19×22×36 in · seat ≈ 18 in',
  },
  {
    id: 'dining-armchair',
    name: 'Dining Armchair',
    category: 'Seating',
    subcategory: 'Chairs',
    dims: [0.58, 0.58, 0.91],
    color: '#9a6e4a',
    price: 229,
    emoji: '🪑',
    thumbnailUrl: '/catalog/thumbs/chair.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['chair', 'dining', 'armchair'],
    roomTypes: ['Dining room', 'Kitchen'],
    note: '≈ 23×23×36 in',
  },
  {
    id: 'counter-stool',
    name: 'Counter-Height Stool',
    category: 'Seating',
    subcategory: 'Stools',
    dims: [0.46, 0.48, 1.02],
    color: '#6b5340',
    price: 179,
    emoji: ' Conting',
    thumbnailUrl: '/catalog/thumbs/stool.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['stool', 'counter', 'kitchen'],
    roomTypes: ['Kitchen', 'Dining room'],
    note: '≈ 18×19×40 in · seat ≈ 24–26 in for 36 in counters',
  },
  {
    id: 'bar-stool',
    name: 'Bar-Height Stool',
    category: 'Seating',
    subcategory: 'Stools',
    dims: [0.46, 0.48, 1.14],
    color: '#5f4a3a',
    price: 189,
    emoji: ' Conting',
    thumbnailUrl: '/catalog/thumbs/stool.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['stool', 'bar'],
    roomTypes: ['Kitchen', 'Dining room', 'Living room'],
    note: '≈ 18×19×45 in · seat ≈ 30 in for 42 in bars',
  },
  {
    id: 'office-task-chair',
    name: 'Office Task Chair',
    category: 'Seating',
    subcategory: 'Chairs',
    dims: [0.66, 0.66, 1.12],
    color: '#3a3f45',
    price: 329,
    emoji: '🪑',
    thumbnailUrl: '/catalog/thumbs/chair.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['chair', 'office', 'desk'],
    roomTypes: ['Office'],
    note: '≈ 26×26×44 in',
  },
  {
    id: 'entry-bench',
    name: 'Entry Bench with Storage',
    category: 'Seating',
    subcategory: 'Benches',
    dims: [1.22, 0.41, 0.48],
    color: '#7d6550',
    price: 249,
    emoji: '▬',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bench', 'entry', 'hallway'],
    roomTypes: ['Hallway', 'Bedroom', 'Living room'],
    note: '≈ 48×16×19 in',
  },

  // ── Tables & consoles ────────────────────────────────────────────────
  {
    id: 'dining-table-four',
    name: 'Dining Table for Four',
    category: 'Tables',
    subcategory: 'Dining',
    dims: [1.22, 0.91, 0.76],
    color: '#8b6540',
    price: 599,
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['table', 'dining'],
    roomTypes: ['Dining room', 'Kitchen'],
    note: '≈ 48×36×30 in',
  },
  {
    id: 'dining-table-six',
    name: 'Dining Table for Six',
    category: 'Tables',
    subcategory: 'Dining',
    dims: [1.83, 0.97, 0.76],
    color: '#855f3c',
    price: 899,
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['table', 'dining'],
    roomTypes: ['Dining room', 'Kitchen'],
    note: '≈ 72×38×30 in',
  },
  {
    id: 'dining-table-eight',
    name: 'Dining Table for Eight',
    category: 'Tables',
    subcategory: 'Dining',
    dims: [2.44, 1.02, 0.76],
    color: '#7f5938',
    price: 1299,
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['table', 'dining'],
    roomTypes: ['Dining room'],
    note: '≈ 96×40×30 in',
  },
  {
    id: 'round-dining-table',
    name: 'Round Dining Table',
    category: 'Tables',
    subcategory: 'Dining',
    dims: [1.22, 1.22, 0.76],
    color: '#8a633e',
    price: 749,
    emoji: '●',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['table', 'dining', 'round'],
    roomTypes: ['Dining room', 'Kitchen'],
    note: '≈ 48 in diameter × 30 in H',
  },
  {
    id: 'coffee-table-rectangular',
    name: 'Rectangular Coffee Table',
    category: 'Tables',
    subcategory: 'Living',
    dims: [1.22, 0.66, 0.43],
    color: '#5a524a',
    price: 349,
    emoji: '●',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['table', 'coffee'],
    roomTypes: ['Living room'],
    note: '≈ 48×26×17 in',
  },
  {
    id: 'console-entry',
    name: 'Entry Console Table',
    category: 'Tables',
    subcategory: 'Consoles',
    dims: [1.27, 0.36, 0.81],
    color: '#6e5744',
    price: 399,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['console', 'entry', 'hallway'],
    roomTypes: ['Hallway', 'Living room', 'Dining room'],
    note: '≈ 50×14×32 in — slim against wall',
  },
  {
    id: 'console-living',
    name: 'Living Room Console',
    category: 'Tables',
    subcategory: 'Consoles',
    dims: [1.52, 0.41, 0.81],
    color: '#655040',
    price: 449,
    emoji: '▭',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['console', 'sofa-table'],
    roomTypes: ['Living room', 'Hallway'],
    note: '≈ 60×16×32 in — behind sofa or against wall',
  },
  {
    id: 'media-console',
    name: 'Media Console / TV Stand',
    category: 'Tables',
    subcategory: 'Media',
    dims: [1.83, 0.46, 0.56],
    color: '#4a4540',
    price: 549,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['media', 'tv', 'console'],
    roomTypes: ['Living room', 'Bedroom'],
    note: '≈ 72×18×22 in',
  },
  {
    id: 'desk-writing',
    name: 'Writing Desk',
    category: 'Tables',
    subcategory: 'Desks',
    dims: [1.22, 0.61, 0.76],
    color: '#7a624c',
    price: 429,
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['desk', 'office'],
    roomTypes: ['Office', 'Bedroom'],
    note: '≈ 48×24×30 in',
  },
  {
    id: 'desk-executive',
    name: 'Executive Desk',
    category: 'Tables',
    subcategory: 'Desks',
    dims: [1.68, 0.76, 0.76],
    color: '#6a5340',
    price: 899,
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['desk', 'office'],
    roomTypes: ['Office'],
    note: '≈ 66×30×30 in',
  },

  // ── Storage ──────────────────────────────────────────────────────────
  {
    id: 'dresser-double',
    name: 'Double Dresser',
    category: 'Storage',
    subcategory: 'Dressers',
    dims: [1.52, 0.48, 0.86],
    color: '#8b7355',
    price: 699,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['dresser', 'bedroom'],
    roomTypes: ['Bedroom'],
    note: '≈ 60×19×34 in',
  },
  {
    id: 'dresser-tall',
    name: 'Tall Chest of Drawers',
    category: 'Storage',
    subcategory: 'Dressers',
    dims: [0.91, 0.48, 1.32],
    color: '#7e664c',
    price: 599,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['dresser', 'chest', 'bedroom'],
    roomTypes: ['Bedroom', 'Children’s room'],
    note: '≈ 36×19×52 in',
  },
  {
    id: 'wardrobe-double',
    name: 'Double Wardrobe',
    category: 'Storage',
    subcategory: 'Wardrobes',
    dims: [1.52, 0.61, 2.13],
    color: '#6a5542',
    price: 999,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['wardrobe', 'closet'],
    roomTypes: ['Bedroom', 'Storage / wardrobe'],
    note: '≈ 60×24×84 in',
  },
  {
    id: 'sideboard',
    name: 'Dining Sideboard',
    category: 'Storage',
    subcategory: 'Sideboards',
    dims: [1.83, 0.46, 0.86],
    color: '#745a44',
    price: 799,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['sideboard', 'buffet', 'dining'],
    roomTypes: ['Dining room', 'Living room', 'Hallway'],
    note: '≈ 72×18×34 in',
  },
  {
    id: 'bookshelf-tall',
    name: 'Tall Bookshelf',
    category: 'Storage',
    subcategory: 'Shelving',
    dims: [0.91, 0.36, 2.03],
    color: '#7a5f45',
    price: 449,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/bookshelf.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['bookshelf', 'storage'],
    roomTypes: ['Living room', 'Office', 'Bedroom', 'Hallway'],
    note: '≈ 36×14×80 in',
  },
  {
    id: 'filing-cabinet',
    name: 'Two-Drawer File Cabinet',
    category: 'Storage',
    subcategory: 'Office',
    dims: [0.41, 0.56, 0.71],
    color: '#4a4e52',
    price: 179,
    emoji: '▥',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['file', 'office'],
    roomTypes: ['Office'],
    note: '≈ 16×22×28 in',
  },
  {
    id: 'laundry-hamper',
    name: 'Laundry Hamper Cabinet',
    category: 'Storage',
    subcategory: 'Laundry',
    dims: [0.61, 0.46, 0.91],
    color: '#8a7a68',
    price: 159,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['laundry', 'hamper'],
    roomTypes: ['Laundry', 'Bathroom', 'Bathroom'],
    note: '≈ 24×18×36 in',
  },

  // ── Cabinetry (standard modular sizes) ───────────────────────────────
  {
    id: 'base-cab-15',
    name: 'Base Cabinet 15″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.381, 0.61, 0.876],
    color: '#ebe6dc',
    price: 289,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'base', 'kitchen'],
    roomTypes: ['Kitchen', 'Bathroom', 'Laundry'],
    note: '15×24×34.5 in standard base',
  },
  {
    id: 'base-cab-18',
    name: 'Base Cabinet 18″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.457, 0.61, 0.876],
    color: '#e8e3d9',
    price: 319,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'base', 'kitchen'],
    roomTypes: ['Kitchen', 'Bathroom', 'Laundry'],
    note: '18×24×34.5 in',
  },
  {
    id: 'base-cab-24',
    name: 'Base Cabinet 24″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.61, 0.61, 0.876],
    color: '#e5e0d6',
    price: 349,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'base', 'kitchen'],
    roomTypes: ['Kitchen', 'Bathroom', 'Laundry'],
    note: '24×24×34.5 in',
  },
  {
    id: 'base-cab-30',
    name: 'Base Cabinet 30″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.762, 0.61, 0.876],
    color: '#e2ddd3',
    price: 389,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'base', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '30×24×34.5 in',
  },
  {
    id: 'base-cab-36',
    name: 'Base Cabinet 36″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.914, 0.61, 0.876],
    color: '#dfdacf',
    price: 429,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'base', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '36×24×34.5 in',
  },
  {
    id: 'base-cab-sink-36',
    name: 'Sink Base Cabinet 36″',
    category: 'Cabinetry',
    subcategory: 'Base',
    dims: [0.914, 0.61, 0.876],
    color: '#dcd7cc',
    price: 449,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'sink', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '36×24×34.5 in sink base',
  },
  {
    id: 'wall-cab-30x30',
    name: 'Wall Cabinet 30×30″',
    category: 'Cabinetry',
    subcategory: 'Wall',
    dims: [0.762, 0.305, 0.762],
    color: '#f0ebe2',
    price: 279,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'wall',
    placementSurfaces: ['wall'],
    tags: ['cabinet', 'wall', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '30 W × 12 D × 30 H in',
  },
  {
    id: 'wall-cab-36x30',
    name: 'Wall Cabinet 36×30″',
    category: 'Cabinetry',
    subcategory: 'Wall',
    dims: [0.914, 0.305, 0.762],
    color: '#ede8df',
    price: 319,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'wall',
    placementSurfaces: ['wall'],
    tags: ['cabinet', 'wall', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '36 W × 12 D × 30 H in',
  },
  {
    id: 'wall-cab-30x42',
    name: 'Wall Cabinet 30×42″',
    category: 'Cabinetry',
    subcategory: 'Wall',
    dims: [0.762, 0.305, 1.067],
    color: '#ebe6dd',
    price: 349,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'wall',
    placementSurfaces: ['wall'],
    tags: ['cabinet', 'wall', 'kitchen'],
    roomTypes: ['Kitchen'],
    note: '30 W × 12 D × 42 H in',
  },
  {
    id: 'pantry-cabinet-24',
    name: 'Tall Pantry Cabinet 24″',
    category: 'Cabinetry',
    subcategory: 'Tall',
    dims: [0.61, 0.61, 2.134],
    color: '#e8e3da',
    price: 899,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/cabinet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['cabinet', 'pantry', 'tall'],
    roomTypes: ['Kitchen', 'Laundry', 'Storage / wardrobe'],
    note: '24×24×84 in',
  },
  {
    id: 'island-base-60',
    name: 'Kitchen Island Base 60″',
    category: 'Cabinetry',
    subcategory: 'Island',
    dims: [1.524, 0.914, 0.914],
    color: '#ddd8ce',
    price: 1299,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/island.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['island', 'kitchen', 'cabinet'],
    roomTypes: ['Kitchen'],
    note: '60×36×36 in island carcass (before countertop)',
  },
  {
    id: 'vanity-30',
    name: 'Bathroom Vanity 30″',
    category: 'Cabinetry',
    subcategory: 'Vanity',
    dims: [0.762, 0.533, 0.864],
    color: '#e6e1d8',
    price: 549,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['vanity', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '30×21×34 in',
  },
  {
    id: 'vanity-36',
    name: 'Bathroom Vanity 36″',
    category: 'Cabinetry',
    subcategory: 'Vanity',
    dims: [0.914, 0.533, 0.864],
    color: '#e3ded5',
    price: 649,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['vanity', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '36×21×34 in',
  },
  {
    id: 'vanity-60-double',
    name: 'Double Vanity 60″',
    category: 'Cabinetry',
    subcategory: 'Vanity',
    dims: [1.524, 0.559, 0.864],
    color: '#e0dbd2',
    price: 1099,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['vanity', 'bathroom', 'double'],
    roomTypes: ['Bathroom'],
    note: '60×22×34 in',
  },

  // ── Countertops (placeable sections) ─────────────────────────────────
  {
    id: 'counter-run-8ft',
    name: 'Countertop Run 8′',
    category: 'Surfaces',
    subcategory: 'Countertops',
    dims: [2.438, 0.648, 0.038],
    color: '#e8e4dc',
    price: 1200,
    priceUnit: 'each',
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/counter.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    material: 'Quartz / stone',
    tags: ['countertop', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry', 'Bathroom'],
    note: '96×25.5×1.5 in — standard depth over base cabinets',
  },
  {
    id: 'counter-run-10ft',
    name: 'Countertop Run 10′',
    category: 'Surfaces',
    subcategory: 'Countertops',
    dims: [3.048, 0.648, 0.038],
    color: '#e5e1d9',
    price: 1500,
    priceUnit: 'each',
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/counter.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['countertop', 'kitchen'],
    roomTypes: ['Kitchen', 'Laundry'],
    note: '120×25.5×1.5 in',
  },
  {
    id: 'island-top-60x36',
    name: 'Island Countertop 60×36″',
    category: 'Surfaces',
    subcategory: 'Countertops',
    dims: [1.524, 0.914, 0.038],
    color: '#e2ded6',
    price: 980,
    priceUnit: 'each',
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/island.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['countertop', 'island'],
    roomTypes: ['Kitchen'],
    note: '60×36×1.5 in island top',
  },
  {
    id: 'island-top-84x40',
    name: 'Island Countertop 84×40″',
    category: 'Surfaces',
    subcategory: 'Countertops',
    dims: [2.134, 1.016, 0.038],
    color: '#dfdbd3',
    price: 1450,
    priceUnit: 'each',
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/island.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['countertop', 'island'],
    roomTypes: ['Kitchen'],
    note: '84×40×1.5 in — overhang seating side',
  },
  {
    id: 'vanity-top-36',
    name: 'Vanity Top 36″',
    category: 'Surfaces',
    subcategory: 'Countertops',
    dims: [0.914, 0.559, 0.032],
    color: '#f2efe8',
    price: 320,
    priceUnit: 'each',
    emoji: '▰',
    thumbnailUrl: '/catalog/thumbs/counter.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['vanity', 'countertop', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '36×22×1.25 in',
  },

  // ── Trim / moldings ──────────────────────────────────────────────────
  {
    id: 'crown-molding-classic',
    name: 'Classic Crown Molding 4½″',
    category: 'Trim',
    subcategory: 'Crown',
    dims: [1, 0.06, 0.114],
    color: '#f7f4ed',
    price: 5.25,
    priceUnit: 'linear ft',
    emoji: '⌐',
    mountingType: 'ceiling',
    placementSurfaces: ['ceiling'],
    placementMode: 'ceiling-perimeter',
    tags: ['trim', 'crown', 'molding'],
    roomTypes: ['Bedroom', 'Living room', 'Dining room', 'Office', 'Hallway', 'Children’s room', 'Bathroom', 'Kitchen', 'Laundry'],
    note: '≈ 4.5 in profile · applies along ceiling–wall junction',
  },
  {
    id: 'crown-molding-large',
    name: 'Large Crown Molding 6″',
    category: 'Trim',
    subcategory: 'Crown',
    dims: [1, 0.08, 0.152],
    color: '#f5f2eb',
    price: 7.5,
    priceUnit: 'linear ft',
    emoji: '⌐',
    mountingType: 'ceiling',
    placementSurfaces: ['ceiling'],
    placementMode: 'ceiling-perimeter',
    tags: ['trim', 'crown', 'molding'],
    roomTypes: ['Bedroom', 'Living room', 'Dining room', 'Office', 'Hallway', 'Children’s room', 'Bathroom', 'Kitchen', 'Laundry'],
    note: '≈ 6 in profile for taller ceilings',
  },
  {
    id: 'baseboard-tall',
    name: 'Tall Baseboard 5¼″',
    category: 'Trim',
    subcategory: 'Baseboard',
    dims: [1, 0.018, 0.133],
    color: '#f8f5ee',
    price: 3.5,
    priceUnit: 'linear ft',
    emoji: '▬',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-perimeter',
    tags: ['trim', 'baseboard'],
    roomTypes: ['Bedroom', 'Living room', 'Dining room', 'Office', 'Hallway', 'Children’s room', 'Bathroom', 'Kitchen', 'Laundry'],
    note: '≈ 5.25 in tall modern base',
  },
  {
    id: 'chair-rail',
    name: 'Chair Rail',
    category: 'Trim',
    subcategory: 'Chair rail',
    dims: [1, 0.04, 0.07],
    color: '#f4f1ea',
    price: 2.95,
    priceUnit: 'linear ft',
    emoji: '▬',
    thumbnailUrl: '/catalog/thumbs/chair.svg',
    mountingType: 'wall',
    placementSurfaces: ['wall'],
    tags: ['trim', 'chair-rail'],
    roomTypes: ['Dining room', 'Hallway', 'Living room'],
    note: '≈ 2.75 in profile · place on wall at ~32–36 in AFF',
  },

  // ── Lighting ─────────────────────────────────────────────────────────
  {
    id: 'table-lamp',
    name: 'Table Lamp',
    category: 'Lighting',
    subcategory: 'Lamps',
    dims: [0.36, 0.36, 0.66],
    color: '#d8d2c8',
    price: 89,
    emoji: '◉',
    thumbnailUrl: '/catalog/thumbs/table.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['lamp', 'table'],
    roomTypes: ['Bedroom', 'Living room', 'Office'],
    note: '≈ 14×14×26 in — place on nightstand / console',
  },
  {
    id: 'pendant-dining',
    name: 'Dining Pendant Light',
    category: 'Lighting',
    subcategory: 'Pendants',
    dims: [0.46, 0.46, 0.71],
    color: '#2c3034',
    price: 249,
    emoji: '◉',
    mountingType: 'ceiling',
    placementSurfaces: ['ceiling'],
    tags: ['pendant', 'dining', 'light'],
    roomTypes: ['Dining room', 'Kitchen'],
    note: '≈ 18 in diameter · hang over table',
  },
  {
    id: 'flush-mount-ceiling',
    name: 'Flush-Mount Ceiling Light',
    category: 'Lighting',
    subcategory: 'Ceiling',
    dims: [0.38, 0.38, 0.14],
    color: '#e8e6e2',
    price: 79,
    emoji: '☼',
    mountingType: 'ceiling',
    placementSurfaces: ['ceiling'],
    tags: ['ceiling', 'light'],
    roomTypes: ['Hallway', 'Bedroom', 'Bathroom', 'Laundry', 'Kitchen'],
    note: '≈ 15 in diameter × 5.5 in H',
  },

  // ── Plumbing fixtures (placeable) ────────────────────────────────────
  {
    id: 'toilet-standard',
    name: 'Standard Toilet',
    category: 'Plumbing',
    subcategory: 'Fixtures',
    dims: [0.48, 0.74, 0.78],
    color: '#f5f5f3',
    price: 329,
    emoji: '▢',
    thumbnailUrl: '/catalog/thumbs/toilet.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['toilet', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '≈ 19×29×31 in rough footprint',
  },
  {
    id: 'freestanding-tub',
    name: 'Freestanding Bathtub',
    category: 'Plumbing',
    subcategory: 'Fixtures',
    dims: [1.68, 0.81, 0.61],
    color: '#f0eeea',
    price: 1899,
    emoji: '▭',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['tub', 'bathtub', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '≈ 66×32×24 in',
  },
  {
    id: 'shower-base-36',
    name: 'Shower Base 36×36″',
    category: 'Plumbing',
    subcategory: 'Fixtures',
    dims: [0.914, 0.914, 0.08],
    color: '#e8e6e2',
    price: 289,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/shower.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['shower', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '36×36 in acrylic base',
  },
  {
    id: 'shower-base-60',
    name: 'Shower Base 60×32″',
    category: 'Plumbing',
    subcategory: 'Fixtures',
    dims: [1.524, 0.813, 0.08],
    color: '#e6e4e0',
    price: 389,
    emoji: '▦',
    thumbnailUrl: '/catalog/thumbs/shower.svg',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['shower', 'bathroom'],
    roomTypes: ['Bathroom'],
    note: '60×32 in acrylic base',
  },

  // ── Textiles / rugs ───────────────────────────────────────────────────
  {
    id: 'rug-8x10',
    name: 'Area Rug 8×10′',
    category: 'Textiles',
    subcategory: 'Rugs',
    dims: [3.05, 2.44, 0.02],
    color: '#8b5e4a',
    price: 449,
    emoji: '▭',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['rug', 'textile'],
    roomTypes: ['Living room', 'Bedroom', 'Dining room', 'Office'],
    note: '8×10 ft',
  },
  {
    id: 'rug-5x8',
    name: 'Area Rug 5×8′',
    category: 'Textiles',
    subcategory: 'Rugs',
    dims: [2.44, 1.52, 0.02],
    color: '#7a6a58',
    price: 279,
    emoji: '▭',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['rug', 'textile'],
    roomTypes: ['Bedroom', 'Living room', 'Office', 'Hallway'],
    note: '5×8 ft',
  },
  {
    id: 'runner-hallway',
    name: 'Hallway Runner 2.5×8′',
    category: 'Textiles',
    subcategory: 'Rugs',
    dims: [2.44, 0.76, 0.015],
    color: '#6e5a48',
    price: 159,
    emoji: '▬',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['rug', 'runner', 'hallway'],
    roomTypes: ['Hallway', 'Kitchen'],
    note: '2.5×8 ft runner',
  },

  // ── Appliances (common sizes) ────────────────────────────────────────
  {
    id: 'dishwasher-24',
    name: 'Dishwasher 24″',
    category: 'Appliances',
    subcategory: 'Kitchen',
    dims: [0.61, 0.61, 0.876],
    color: '#c5c8c9',
    price: 799,
    emoji: '▣',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['dishwasher', 'kitchen'],
    roomTypes: ['Kitchen'],
    note: '24×24×34.5 in',
  },
  {
    id: 'range-30',
    name: 'Freestanding Range 30″',
    category: 'Appliances',
    subcategory: 'Kitchen',
    dims: [0.762, 0.686, 0.914],
    color: '#b0b4b5',
    price: 1099,
    emoji: '▤',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['range', 'stove', 'kitchen'],
    roomTypes: ['Kitchen'],
    note: '30×27×36 in',
  },
  {
    id: 'fridge-36-french',
    name: 'French-Door Refrigerator 36″',
    category: 'Appliances',
    subcategory: 'Kitchen',
    dims: [0.914, 0.84, 1.78],
    color: '#d0d2d1',
    price: 2499,
    emoji: '▣',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['refrigerator', 'kitchen'],
    roomTypes: ['Kitchen'],
    note: '≈ 36×33×70 in',
  },
  {
    id: 'washer-27',
    name: 'Front-Load Washer',
    category: 'Appliances',
    subcategory: 'Laundry',
    dims: [0.686, 0.813, 0.991],
    color: '#d8d9d7',
    price: 999,
    emoji: '▣',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['washer', 'laundry'],
    roomTypes: ['Laundry'],
    note: '≈ 27×32×39 in',
  },
  {
    id: 'dryer-27',
    name: 'Front-Load Dryer',
    category: 'Appliances',
    subcategory: 'Laundry',
    dims: [0.686, 0.813, 0.991],
    color: '#d4d5d3',
    price: 949,
    emoji: '▣',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    tags: ['dryer', 'laundry'],
    roomTypes: ['Laundry'],
    note: '≈ 27×32×39 in',
  },
];
