/**
 * Room flooring finishes — apply via floor-fill (tap product, then tap a room).
 * Textures live under /public/catalog/floors and show in 3D when applied.
 */
export const residentialFlooring = [
  {
    id: 'floor-oak-hardwood',
    name: 'White Oak Hardwood',
    category: 'Flooring',
    subcategory: 'Hardwood',
    dims: [0.127, 0.019, 1.219],
    color: '#c9a57a',
    price: 8.5,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'White oak',
    finish: 'Natural matte',
    textureUrl: '/catalog/floors/hardwood-oak.svg',
    textureRepeat: 0.35,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'hardwood', 'wood'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Dining room',
      'Office',
      'Hallway',
      'Children’s room',
      'Kitchen',
    ],
    note: '5×48 in plank look · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-walnut-hardwood',
    name: 'Walnut Hardwood',
    category: 'Flooring',
    subcategory: 'Hardwood',
    dims: [0.127, 0.019, 1.219],
    color: '#6b4a32',
    price: 11,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Walnut',
    finish: 'Satin',
    textureUrl: '/catalog/floors/hardwood-walnut.svg',
    textureRepeat: 0.4,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'hardwood', 'wood'],
    roomTypes: ['Bedroom', 'Living room', 'Dining room', 'Office', 'Hallway'],
    note: 'Wide-plank walnut · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-ash-laminate',
    name: 'Ash Laminate Plank',
    category: 'Flooring',
    subcategory: 'Laminate',
    dims: [0.19, 0.008, 1.38],
    color: '#d7cfc3',
    price: 3.25,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Laminate',
    finish: 'Wood-look',
    textureUrl: '/catalog/floors/laminate-ash.svg',
    textureRepeat: 0.28,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'laminate'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Dining room',
      'Office',
      'Hallway',
      'Children’s room',
      'Kitchen',
      'Laundry',
    ],
    note: 'Click-lock laminate · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-vinyl-gray',
    name: 'Gray Luxury Vinyl Plank',
    category: 'Flooring',
    subcategory: 'Vinyl',
    dims: [0.178, 0.005, 1.219],
    color: '#8f9194',
    price: 4.75,
    priceUnit: 'sq ft' as const,
    emoji: '▥',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'LVP',
    finish: 'Waterproof',
    textureUrl: '/catalog/floors/vinyl-plank-gray.svg',
    textureRepeat: 0.3,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'vinyl', 'lvp'],
    roomTypes: [
      'Bedroom',
      'Living room',
      'Kitchen',
      'Bathroom',
      'Laundry',
      'Hallway',
      'Children’s room',
      'Office',
    ],
    note: 'Waterproof LVP · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-concrete-polished',
    name: 'Polished Concrete',
    category: 'Flooring',
    subcategory: 'Concrete',
    dims: [1, 0.1, 1],
    color: '#9b9b98',
    price: 6.5,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Concrete',
    finish: 'Polished',
    textureUrl: '/catalog/floors/concrete-polished.svg',
    textureRepeat: 1.2,
    thumbnailUrl: '/catalog/thumbs/floor-concrete.svg',
    tags: ['flooring', 'concrete'],
    roomTypes: ['Living room', 'Kitchen', 'Laundry', 'Hallway', 'Outdoor'],
    note: 'Sealed polished slab look · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-ceramic-white',
    name: 'White Ceramic Floor Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.305, 0.01, 0.305],
    color: '#e8e6e1',
    price: 4.5,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Ceramic',
    finish: 'Matte',
    textureUrl: '/catalog/floors/tile-ceramic-white.svg',
    textureRepeat: 0.32,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'ceramic'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry', 'Hallway'],
    note: '12×12 in ceramic · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-porcelain-gray',
    name: 'Gray Porcelain Plank Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.3048, 0.01, 0.6096],
    color: '#9aa0a6',
    price: 5.75,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Porcelain',
    finish: 'Rectified',
    textureUrl: '/catalog/floors/tile-porcelain-gray.svg',
    textureRepeat: 0.45,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'porcelain'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry', 'Hallway', 'Living room'],
    note: '12×24 in porcelain · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-tile-hex-stone',
    name: 'Hexagon Stone Mosaic',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.305, 0.01, 0.305],
    color: '#c2b7a6',
    price: 9.25,
    priceUnit: 'sq ft' as const,
    emoji: '⬡',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Natural stone look',
    finish: 'Honed',
    textureUrl: '/catalog/floors/tile-hex-stone.svg',
    textureRepeat: 0.4,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'mosaic'],
    roomTypes: ['Bathroom', 'Kitchen', 'Hallway', 'Laundry'],
    note: 'Hex mosaic field · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-subway-tile',
    name: 'Subway Ceramic Floor Tile',
    category: 'Flooring',
    subcategory: 'Tile',
    dims: [0.152, 0.01, 0.076],
    color: '#f7f5f1',
    price: 3.9,
    priceUnit: 'sq ft' as const,
    emoji: '▦',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Ceramic',
    finish: 'Gloss',
    textureUrl: '/catalog/floors/tile-subway-white.svg',
    textureRepeat: 0.22,
    thumbnailUrl: '/catalog/thumbs/floor-tile.svg',
    tags: ['flooring', 'tile', 'subway'],
    roomTypes: ['Bathroom', 'Kitchen', 'Laundry'],
    note: '3×6 in subway laid running bond · tap then tap a room to fill the floor',
  },
  {
    id: 'floor-carpet-beige',
    name: 'Beige Loop Carpet',
    category: 'Flooring',
    subcategory: 'Carpet',
    dims: [3.66, 0.012, 3.66],
    color: '#c4aa88',
    price: 3.8,
    priceUnit: 'sq ft' as const,
    emoji: '▭',
    mountingType: 'floor',
    placementSurfaces: ['floor'],
    placementMode: 'floor-fill' as const,
    material: 'Nylon loop',
    finish: 'Soft',
    textureUrl: '/catalog/floors/carpet-beige.svg',
    textureRepeat: 0.8,
    roughness: 1,
    thumbnailUrl: '/catalog/thumbs/floor-wood.svg',
    tags: ['flooring', 'carpet'],
    roomTypes: ['Bedroom', 'Living room', 'Office', 'Children’s room', 'Hallway'],
    note: 'Broadloom carpet look · tap then tap a room to fill the floor',
  },
];
