import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Circle, Layer, Line, Stage } from 'react-konva';
import type Konva from 'konva';
import type {Opening,Wall} from '../../types';
import { snapWallPoint,wallLengthMeters } from '../../lib/geometry/snapping';
import {formatLength,parseLength} from '../../lib/measurements';
import { usePlannerStore } from '../../store/plannerStore';
import { Grid } from './Grid';
import { WallShape } from './WallShape';

export function FloorPlanEditor(){
 const host=useRef<HTMLDivElement>(null),nextCursor=useRef({x:0,y:0}),frame=useRef<number|null>(null),gesture=useRef<{x:number;y:number;time:number;point:{x:number;y:number};onStage:boolean}|null>(null);
 const [size,setSize]=useState({width:1,height:1}),[cursor,setCursor]=useState({x:0,y:0});
 const walls=usePlannerStore(s=>s.walls),openings=usePlannerStore(s=>s.openings),tool=usePlannerStore(s=>s.tool),draftStart=usePlannerStore(s=>s.draftStart),selectedWallId=usePlannerStore(s=>s.selectedWallId),selectedOpeningId=usePlannerStore(s=>s.selectedOpeningId),unitSystem=usePlannerStore(s=>s.unitSystem);
 const setDraftStart=usePlannerStore(s=>s.setDraftStart),addWall=usePlannerStore(s=>s.addWall),updateWallEndpoint=usePlannerStore(s=>s.updateWallEndpoint),selectWall=usePlannerStore(s=>s.selectWall),selectOpening=usePlannerStore(s=>s.selectOpening),addOpening=usePlannerStore(s=>s.addOpening),updateOpening=usePlannerStore(s=>s.updateOpening);
 const openingsByWall=useMemo(()=>{const map=new Map<string,typeof openings>();for(const opening of openings){const list=map.get(opening.wallId);if(list)list.push(opening);else map.set(opening.wallId,[opening])}return map},[openings]);
 const scale=size.width<650?Math.max(.42,size.width/760):1,logicalWidth=size.width/scale,logicalHeight=size.height/scale;
 useLayoutEffect(()=>{const el=host.current;if(!el)return;const measure=()=>{const r=el.getBoundingClientRect();setSize({width:Math.max(1,r.width),height:Math.max(1,r.height)})};measure();const ro=new ResizeObserver(measure);ro.observe(el);return()=>ro.disconnect()},[]);
 useEffect(()=>()=>{if(frame.current!==null)cancelAnimationFrame(frame.current)},[]);
 const point=(stage:Konva.Stage)=>snapWallPoint(stage.getRelativePointerPosition()??{x:0,y:0},walls);
 const move=(e:Konva.KonvaEventObject<PointerEvent>)=>{if(!e.evt.isPrimary||e.evt.pointerType==='touch')return;nextCursor.current=point(e.target.getStage()!);if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;setCursor(nextCursor.current)})};
 const activate=(p:{x:number;y:number})=>{if(tool==='wall'){if(!draftStart){setDraftStart(p);setCursor(p)}else{addWall(draftStart,p);setDraftStart(null)}}else{selectOpening(null);selectWall(null)}};
 const pointerDown=(e:Konva.KonvaEventObject<PointerEvent>)=>{if(!e.evt.isPrimary)return;const p=point(e.target.getStage()!);gesture.current={x:e.evt.clientX,y:e.evt.clientY,time:performance.now(),point:p,onStage:e.target===e.target.getStage()};if(e.evt.pointerType==='touch')setCursor(p)};
 const pointerUp=(e:Konva.KonvaEventObject<PointerEvent>)=>{const start=gesture.current;gesture.current=null;if(!start||!start.onStage||!e.evt.isPrimary)return;const distance=Math.hypot(e.evt.clientX-start.x,e.evt.clientY-start.y),maxDistance=e.evt.pointerType==='touch'?12:8;if(distance<=maxDistance&&performance.now()-start.time<700)activate(start.point)};
 const selectedOpening=openings.find(o=>o.id===selectedOpeningId),selectedWall=walls.find(w=>w.id===selectedWallId);
 return <div className="canvas-host" ref={host}><Stage width={size.width} height={size.height} scaleX={scale} scaleY={scale} onPointerMove={move} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={()=>{gesture.current=null}}>
  <Layer><Grid width={logicalWidth} height={logicalHeight}/>{walls.map(w=><WallShape key={w.id} wall={w} tool={tool} openings={openingsByWall.get(w.id)??[]} selected={w.id===selectedWallId} selectedOpeningId={selectedOpeningId} unitSystem={unitSystem} onSelect={()=>selectWall(w.id)} onOpening={type=>addOpening(w.id,type)} onOpeningSelect={selectOpening} onOpeningMove={(id,offset)=>updateOpening(id,{offset})} onEndpointMove={(end,x,y)=>updateWallEndpoint(w.id,end,snapWallPoint({x,y},walls,w.id))}/>) }
  {draftStart&&tool==='wall'&&<><Line points={[draftStart.x,draftStart.y,cursor.x,cursor.y]} stroke="#0058a3" strokeWidth={5} dash={[10,7]} lineCap="round"/><Circle x={cursor.x} y={cursor.y} radius={6} fill="#0058a3"/></>}</Layer>
 </Stage>{tool==='select'&&selectedOpening?<OpeningQuickEditor opening={selectedOpening}/>:tool==='select'&&selectedWall&&<WallQuickEditor wall={selectedWall}/>}<div className="mobile-builder-hint">{tool==='select'?'Tap a wall or opening. Drag handles to resize or move.':tool==='wall'?(draftStart?'Tap once where the wall should end':'Tap once where the wall should start'):`${tool[0].toUpperCase()+tool.slice(1)}: tap a wall`}{draftStart&&<button onClick={()=>setDraftStart(null)}>Cancel</button>}</div><div className="scale">1 square = {unitSystem==='metric'?'25 cm':'10 in'}</div></div>
}

function WallQuickEditor({wall}:{wall:Wall}){const setLength=usePlannerStore(s=>s.setWallLength),split=usePlannerStore(s=>s.splitWall),offset=usePlannerStore(s=>s.offsetWall),unit=usePlannerStore(s=>s.unitSystem);const inputRef=useRef<HTMLInputElement>(null);useEffect(()=>{inputRef.current?.focus();inputRef.current?.select()},[wall.id,unit]);const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const value=parseLength(String(new FormData(e.currentTarget).get('length')??''),unit);if(value)setLength(wall.id,value)};return <div className="wall-quick-editor"><form onSubmit={submit}><label>Exact wall length<input ref={inputRef} key={`${wall.id}-${unit}-${wall.start.x}-${wall.end.x}`} name="length" type="text" defaultValue={unit==='metric'?wallLengthMeters(wall.start,wall.end).toFixed(2):formatLength(wallLengthMeters(wall.start,wall.end),unit)} inputMode="decimal"/><span>{unit==='metric'?'m':'ft / in'}</span></label><button type="submit">Set</button></form><div><button onClick={()=>offset(wall.id,-.25)}>Move out</button><button onClick={()=>split(wall.id)}>Split wall</button><button onClick={()=>offset(wall.id,.25)}>Move in</button></div></div>}

function OpeningQuickEditor({opening}:{opening:Opening}){const update=usePlannerStore(s=>s.updateOpening),remove=usePlannerStore(s=>s.deleteOpening),unit=usePlannerStore(s=>s.unitSystem);const setMeasure=(field:'width'|'height',value:string)=>{const parsed=parseLength(value,unit);if(parsed!==null)update(opening.id,{[field]:parsed})};return <div className="wall-quick-editor opening-quick-editor"><strong>{opening.type[0].toUpperCase()+opening.type.slice(1)}</strong><label>Along wall<input type="range" min=".03" max=".97" step=".01" value={opening.offset} onChange={e=>update(opening.id,{offset:+e.target.value})}/></label><label>Width<input key={`${opening.id}-w-${unit}-${opening.width}`} defaultValue={unit==='metric'?opening.width.toFixed(2):formatLength(opening.width,unit)} onBlur={e=>setMeasure('width',e.target.value)}/></label>{opening.type!=='passage'&&<label>Height<input key={`${opening.id}-h-${unit}-${opening.height}`} defaultValue={unit==='metric'?opening.height.toFixed(2):formatLength(opening.height,unit)} onBlur={e=>setMeasure('height',e.target.value)}/></label>}{opening.type==='door'&&<label>Swing<select value={opening.swing??'left'} onChange={e=>update(opening.id,{swing:e.target.value as Opening['swing']})}><option value="left">Left</option><option value="right">Right</option><option value="none">No swing</option></select></label>}<button className="delete-item" onClick={()=>remove(opening.id)}>Remove</button></div>}
