import type { OwnerJob, PipelineStage, SalesPerformanceBar, TimeMetric } from './types';

const ADAM = 'Adam Horseman';
const JAMES = 'James Manford';
const PAUL = 'Paul Dimeglio';
const RICHARD = 'Richard Linck';
const UNASSIGNED = 'Unassigned';

/**
 * Read-only Olsen Custom Homes snapshot from Buildertrend on 19 Aug 2026.
 * Captured from Jobs List, Work in progress, Daily log creation by job, and Lead Opportunities.
 * Test job "**** Tate TEST JOB" omitted. Closed/Warranty views had no rows.
 * Pending selections, past-due to-dos, and schedule slip were not on list reports (left at 0).
 * Est. close is inferred from days-on-job and BT % complete when BT had no completion date.
 */
const OPEN_JOBS: OwnerJob[] = [
  {
    id: 'bt-allie',
    name: 'Allie Job',
    pm: UNASSIGNED,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-02-07',
    openedAt: '2026-08-03',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Custom new home · projected start Aug 3, 2026. Not on WIP report. 1 daily log (Aug 11).',
  },
  {
    id: 'bt-ahigian',
    name: 'Ahigian - Habashi',
    pm: RICHARD,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 1_628_705.53,
    wip: 0,
    estCloseDate: '2026-12-11',
    openedAt: '2025-10-12',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT revised price $0 · cost % complete 73% · projected costs $1,334,640 · 169 daily logs.',
  },
  {
    id: 'bt-bennett',
    name: 'Bennett',
    pm: JAMES,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_158_353,
    revenueToDate: 626_047.24,
    wip: 532_305.76,
    estCloseDate: '2026-10-17',
    openedAt: '2025-10-07',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 84% complete · 157 daily logs.',
  },
  {
    id: 'bt-blandford',
    name: 'Blandford',
    pm: PAUL,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_298_960.06,
    revenueToDate: 1_289_596.45,
    wip: 9_363.61,
    estCloseDate: '2026-10-01',
    openedAt: '2025-09-26',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 88% complete · 231 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-bucciarelli',
    name: 'Bucciarelli',
    pm: RICHARD,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-01-20',
    openedAt: '2026-06-01',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. Last daily log Jul 24, 2026 (3 logs).',
  },
  {
    id: 'bt-chahlavi',
    name: 'Chahlavi',
    pm: ADAM,
    status: 'open',
    phase: 'design',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_085_163.28,
    revenueToDate: 201_975,
    wip: 883_188.28,
    estCloseDate: '2027-10-23',
    openedAt: '2026-04-19',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 4% complete · 5 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-emerson',
    name: 'Emerson',
    pm: PAUL,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_554_603,
    revenueToDate: 955_406.37,
    wip: 599_196.63,
    estCloseDate: '2026-12-24',
    openedAt: '2025-09-23',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 72% complete · 108 daily logs.',
  },
  {
    id: 'bt-etienne',
    name: 'Etienne',
    pm: ADAM,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_088_116,
    revenueToDate: 329_276.44,
    wip: 758_839.56,
    estCloseDate: '2027-03-11',
    openedAt: '2026-04-28',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 35% complete · 62 daily logs.',
  },
  {
    id: 'bt-goumas',
    name: 'Goumas',
    pm: PAUL,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-01-15',
    openedAt: '2024-09-03',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. Last daily log Apr 11, 2025 (1 log). Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-graham',
    name: 'Graham',
    pm: ADAM,
    status: 'open',
    phase: 'design',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-08-19',
    openedAt: '2026-05-20',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. No daily logs.',
  },
  {
    id: 'bt-jimenez',
    name: 'Jimenez',
    pm: ADAM,
    status: 'open',
    phase: 'closeout',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_154_518,
    revenueToDate: 1_149_705.52,
    wip: 4_812.48,
    estCloseDate: '2026-09-20',
    openedAt: '2025-07-17',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 92% complete · 172 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-kinney',
    name: 'Kinney',
    pm: JAMES,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_255_497.41,
    revenueToDate: 995_399.09,
    wip: 260_098.32,
    estCloseDate: '2026-10-31',
    openedAt: '2025-07-27',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 84% complete · 252 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-lois',
    name: 'Lois',
    pm: PAUL,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_083_711,
    revenueToDate: 798_730.97,
    wip: 284_980.03,
    estCloseDate: '2026-10-29',
    openedAt: '2025-11-04',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 80% complete · 109 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-morris',
    name: 'Morris',
    pm: ADAM,
    status: 'open',
    phase: 'design',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-08-19',
    openedAt: '2026-02-20',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. No daily logs.',
  },
  {
    id: 'bt-moura',
    name: 'Moura',
    pm: RICHARD,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-02-14',
    openedAt: '2025-12-26',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. 1 daily log (Aug 18).',
  },
  {
    id: 'bt-nagle',
    name: 'Nagle',
    pm: ADAM,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_360_391.07,
    revenueToDate: 1_377_463.99,
    wip: 0,
    estCloseDate: '2026-11-19',
    openedAt: '2025-09-01',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 79% complete · invoiced above revised price · 248 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-norris',
    name: 'Norris',
    pm: RICHARD,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-02-14',
    openedAt: '2026-01-03',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. 54 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-olmstead',
    name: 'Olmstead',
    pm: PAUL,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-01-04',
    openedAt: '2026-05-17',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. Last daily log Jul 8, 2026 (2 logs).',
  },
  {
    id: 'bt-peters',
    name: 'Peters',
    pm: PAUL,
    status: 'open',
    phase: 'design',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2027-08-19',
    openedAt: '2026-06-26',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. No daily logs.',
  },
  {
    id: 'bt-pierami',
    name: 'Pierami',
    pm: RICHARD,
    status: 'open',
    phase: 'closeout',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 982_110,
    revenueToDate: 855_641.13,
    wip: 126_468.87,
    estCloseDate: '2026-09-08',
    openedAt: '2025-12-05',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 92% complete · 124 daily logs.',
  },
  {
    id: 'bt-shagnea',
    name: 'Shagnea',
    pm: RICHARD,
    status: 'open',
    phase: 'permitting',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: '2026-12-22',
    openedAt: '2026-05-17',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'Not on WIP report. Last daily log Jun 25, 2026 (3 logs).',
  },
  {
    id: 'bt-veranda',
    name: 'Veranda Bay Model 2',
    pm: JAMES,
    status: 'open',
    phase: 'construction',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 946_367,
    revenueToDate: 0,
    wip: 946_367,
    estCloseDate: '2026-10-13',
    openedAt: '2026-03-12',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 74% complete · WIP report had no amount invoiced · 132 daily logs. Designer Monique Lumley also on the job.',
  },
  {
    id: 'bt-whipple',
    name: 'Whipple',
    pm: ADAM,
    status: 'open',
    phase: 'closeout',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 1_078_675,
    revenueToDate: 1_164_852.51,
    wip: 0,
    estCloseDate: '2026-09-17',
    openedAt: '2025-10-15',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 91% complete · invoiced above revised price · 222 daily logs.',
  },
  {
    id: 'bt-youngs',
    name: 'Youngs/Wolfe',
    pm: PAUL,
    status: 'open',
    phase: 'closeout',
    pendingSelections: 0,
    pastDueTasks: 0,
    contractPrice: 939_194.88,
    revenueToDate: 839_240.47,
    wip: 99_954.41,
    estCloseDate: '2026-09-05',
    openedAt: '2025-11-09',
    slip: { permit: 0, selections: 0, purchasing: 0, construction: 0 },
    notes: 'BT 94% complete · 163 daily logs. Designer Monique Lumley also on the job.',
  },
];

export const LIVE_JOBS: OwnerJob[] = OPEN_JOBS;

/** Open lead opportunities: $43.00M–$50.58M. BT CRM had no proposal/pre-contract dollar buckets. */
export const LIVE_PIPELINE: PipelineStage[] = [
  { id: 'lead', label: 'Lead', value: 43_000_000 },
  { id: 'proposal', label: 'Proposal', value: 0 },
  { id: 'pre-contract', label: 'Pre-Contract', value: 0 },
  { id: 'contract', label: 'Contract', value: 0 },
  { id: 'closed', label: 'Closed / Won', value: 0 },
];

export const LIVE_SALES_PERFORMANCE: SalesPerformanceBar[] = [
  { id: 'backlog', label: 'Signed Backlog', value: 4_505_574.95 },
  { id: 'closings', label: 'Projected Closings', value: 4_154_497.88 },
  { id: 'signing', label: 'Expected Signing Value', value: 43_000_000 },
];

/** BT had no contract/permit/slab-to-close reports. These are days-on-job from the daily-log report. */
export const LIVE_TIME_METRICS: TimeMetric[] = [
  { id: 'contract-close', label: 'Avg. days on job', days: 222, deltaDays: 0 },
  { id: 'permit-close', label: 'Longest job (days)', days: 396, deltaDays: 0 },
  { id: 'slab-close', label: 'Shortest tracked job', days: 39, deltaDays: 0 },
];

export const LIVE_TARGET_MARGIN_PCT = 15;
/** WIP report: $1.392M projected profit / $14.986M revised price. */
export const LIVE_PROJECTED_MARGIN_PCT = 9.3;
/** WIP report earned revenue (12-mo figure was not on the reports opened). */
export const LIVE_ROLLING_REVENUE_12MO = 11_267_690.49;

export const LIVE_SNAPSHOT_AT = '2026-08-19T01:50:00.000Z';
