import type { OwnerJob, PipelineStage, SalesPerformanceBar, TimeMetric } from './types';

/**
 * Read-only Olsen Custom Homes snapshot from Buildertrend (+ Pipedrive when available).
 * Regenerate:
 *   BUILDERTREND_COOKIE=… npm run buildertrend:pull
 *   PIPEDRIVE_API_TOKEN=… npm run pipedrive:pull
 *   npm run buildertrend:update-snapshot
 * Jobs / WIP / logs / tasks / selections = Buildertrend.
 * Sales funnel + weighted pipeline from Pipedrive Sales pipeline (pulled 2026-08-23T10:29:12.296Z).
 * Past due = Tasks Status includes Not completed + due date before today.
 * Pending selections = per job, exclude green Selected/Completed (status 2 and 3).
 * Test job "**** Tate TEST JOB" omitted.
 */
const OPEN_JOBS: OwnerJob[] = [
  {
    id: "bt-40497055",
    name: "Ahigian - Habashi",
    pm: "Richard Linck",
    status: "open",
    phase: "construction",
    pendingSelections: 2,
    pastDueTasks: 19,
    dailyLogsRecentDone: 23,
    dailyLogsTotal: 171,
    foundationStarted: true,
    contractPrice: 2751692.31,
    revenueToDate: 1628705.53,
    wip: 1122986.78,
    estCloseDate: "2026-10-09",
    openedAt: "2025-06-05",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "171 daily logs · BT 73% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 171 daily logs",
  },
  {
    id: "bt-40351917",
    name: "Bennett",
    pm: "James Manford",
    status: "open",
    phase: "construction",
    pendingSelections: 1,
    pastDueTasks: 18,
    dailyLogsRecentDone: 23,
    dailyLogsTotal: 159,
    foundationStarted: true,
    contractPrice: 1158353,
    revenueToDate: 626047.24,
    wip: 532305.76,
    estCloseDate: "2026-09-03",
    openedAt: "2025-05-27",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "159 daily logs · BT 86% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 159 daily logs",
  },
  {
    id: "bt-40228562",
    name: "Blandford",
    pm: "Paul Dimeglio",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 20,
    dailyLogsRecentDone: 21,
    dailyLogsTotal: 233,
    foundationStarted: true,
    contractPrice: 1402571.9,
    revenueToDate: 1289596.45,
    wip: 112975.44999999995,
    estCloseDate: "2026-09-03",
    openedAt: "2025-05-14",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "233 daily logs · BT 83% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 233 daily logs",
  },
  {
    id: "bt-42790290",
    name: "Bucciarelli",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 67,
    pastDueTasks: 15,
    dailyLogsTotal: 3,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-03-22",
    openedAt: "2026-06-04",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · No daily logs · 3 daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2026-07-24 · 3 daily logs",
  },
  {
    id: "bt-42615310",
    name: "Chahlavi",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 17,
    pastDueTasks: 1,
    dailyLogsRecentDone: 3,
    dailyLogsTotal: 7,
    foundationStarted: false,
    contractPrice: 1085163.28,
    revenueToDate: 201975,
    wip: 883188.28,
    estCloseDate: "2027-02-22",
    openedAt: "2026-03-25",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "7 daily logs · BT 5% complete · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2026-08-21 · 7 daily logs",
  },
  {
    id: "bt-40214880",
    name: "Emerson",
    pm: "Paul Dimeglio",
    status: "open",
    phase: "construction",
    pendingSelections: 12,
    pastDueTasks: 16,
    dailyLogsRecentDone: 21,
    dailyLogsTotal: 113,
    foundationStarted: true,
    contractPrice: 1554603,
    revenueToDate: 955406.37,
    wip: 599196.63,
    estCloseDate: "2026-10-29",
    openedAt: "2025-05-09",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "113 daily logs · BT 43% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 113 daily logs",
  },
  {
    id: "bt-42969582",
    name: "Etienne",
    pm: "Adam Horseman",
    status: "open",
    phase: "construction",
    pendingSelections: 3,
    pastDueTasks: 22,
    dailyLogsRecentDone: 19,
    dailyLogsTotal: 66,
    foundationStarted: true,
    contractPrice: 1088116,
    revenueToDate: 329276.44,
    wip: 758839.56,
    estCloseDate: "2026-12-24",
    openedAt: "2026-03-12",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "66 daily logs · BT 41% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 66 daily logs",
  },
  {
    id: "bt-35764730",
    name: "Goumas",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 54,
    pastDueTasks: 12,
    dailyLogsTotal: 1,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-06-16",
    openedAt: "2025-10-09",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · 1 daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2025-04-11 · 1 daily logs",
  },
  {
    id: "bt-44516256",
    name: "Graham",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 67,
    pastDueTasks: 14,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-06-16",
    openedAt: "2026-04-10",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · No daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required)",
  },
  {
    id: "bt-38901121",
    name: "Jimenez",
    pm: "Adam Horseman",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 7,
    dailyLogsRecentDone: 16,
    dailyLogsTotal: 173,
    foundationStarted: true,
    contractPrice: 1244269.35,
    revenueToDate: 1149705.52,
    wip: 94563.83000000007,
    estCloseDate: "2026-09-08",
    openedAt: "2025-01-17",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "173 daily logs · BT 124% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 173 daily logs",
  },
  {
    id: "bt-38215830",
    name: "Kinney",
    pm: "James Manford",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 33,
    dailyLogsRecentDone: 23,
    dailyLogsTotal: 258,
    foundationStarted: true,
    contractPrice: 1513789.57,
    revenueToDate: 995399.09,
    wip: 518390.4800000001,
    estCloseDate: "2026-09-03",
    openedAt: "2025-02-17",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "258 daily logs · BT 90% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 258 daily logs",
  },
  {
    id: "bt-41118068",
    name: "Lois",
    pm: "Paul Dimeglio",
    status: "open",
    phase: "construction",
    pendingSelections: 2,
    pastDueTasks: 9,
    dailyLogsRecentDone: 19,
    dailyLogsTotal: 110,
    foundationStarted: true,
    contractPrice: 1189213.88,
    revenueToDate: 798730.97,
    wip: 390482.9099999999,
    estCloseDate: "2026-10-15",
    openedAt: "2025-07-07",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "110 daily logs · BT 105% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-20 · 110 daily logs",
  },
  {
    id: "bt-45667667",
    name: "Morris",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 67,
    pastDueTasks: 12,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-02-24",
    openedAt: "2026-08-24",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · No daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required)",
  },
  {
    id: "bt-38319441",
    name: "Moura",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 19,
    pastDueTasks: 13,
    dailyLogsRecentDone: 3,
    dailyLogsTotal: 3,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-02-22",
    openedAt: "2025-09-18",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · 3 daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2026-08-20 · 3 daily logs",
  },
  {
    id: "bt-35918575",
    name: "Nagle",
    pm: "Adam Horseman",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 12,
    dailyLogsRecentDone: 20,
    dailyLogsTotal: 250,
    foundationStarted: true,
    contractPrice: 1373646.79,
    revenueToDate: 1377463.99,
    wip: 0,
    estCloseDate: "2026-08-27",
    openedAt: "2025-04-09",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "250 daily logs · BT 114% complete · invoiced above revised price · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 250 daily logs",
  },
  {
    id: "bt-42083349",
    name: "Norris",
    pm: "Richard Linck",
    status: "open",
    phase: "construction",
    pendingSelections: 1,
    pastDueTasks: 10,
    dailyLogsRecentDone: 18,
    dailyLogsTotal: 56,
    foundationStarted: true,
    contractPrice: 1290391.99,
    revenueToDate: 539665.65,
    wip: 750726.34,
    estCloseDate: "2026-10-20",
    openedAt: "2025-09-29",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "56 daily logs · BT 52% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 56 daily logs",
  },
  {
    id: "bt-45275922",
    name: "Olmstead",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 67,
    pastDueTasks: 12,
    dailyLogsRecentDone: 1,
    dailyLogsTotal: 3,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-03-19",
    openedAt: "2026-06-05",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · 3 daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2026-08-21 · 3 daily logs",
  },
  {
    id: "bt-45118977",
    name: "Peters",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 66,
    pastDueTasks: 12,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-03-22",
    openedAt: "2026-06-03",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · No daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required)",
  },
  {
    id: "bt-41776958",
    name: "Pierami",
    pm: "Richard Linck",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 22,
    dailyLogsRecentDone: 22,
    dailyLogsTotal: 126,
    foundationStarted: true,
    contractPrice: 984879.23,
    revenueToDate: 855641.13,
    wip: 129238.09999999998,
    estCloseDate: "2026-09-10",
    openedAt: "2025-08-21",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "126 daily logs · BT 72% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 126 daily logs",
  },
  {
    id: "bt-43331519",
    name: "Shagnea",
    pm: "Unassigned",
    status: "open",
    phase: "design",
    pendingSelections: 67,
    pastDueTasks: 41,
    dailyLogsTotal: 3,
    foundationStarted: false,
    contractPrice: 0,
    revenueToDate: 0,
    wip: 0,
    estCloseDate: "2027-03-22",
    openedAt: "2026-06-24",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "Not on WIP report · 3 daily logs · Site Work not started (Design / Permitting) · Foundation not started (daily logs not required) · Last daily log 2026-06-25 · 3 daily logs",
  },
  {
    id: "bt-42673665",
    name: "Veranda Bay Model 2",
    pm: "James Manford",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 48,
    dailyLogsRecentDone: 21,
    dailyLogsTotal: 135,
    foundationStarted: true,
    contractPrice: 1508343.5,
    revenueToDate: 0,
    wip: 1508343.5,
    estCloseDate: "2026-08-27",
    openedAt: "2026-01-02",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "135 daily logs · BT 93% complete · WIP report had no amount invoiced · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-24 · 135 daily logs",
  },
  {
    id: "bt-38397739",
    name: "Whipple",
    pm: "Adam Horseman",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 6,
    dailyLogsRecentDone: 16,
    dailyLogsTotal: 224,
    foundationStarted: true,
    contractPrice: 1078675,
    revenueToDate: 1164852.51,
    wip: 0,
    estCloseDate: "2026-09-17",
    openedAt: "2025-06-09",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "224 daily logs · BT 106% complete · invoiced above revised price · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-21 · 224 daily logs",
  },
  {
    id: "bt-41200140",
    name: "Youngs/Wolfe",
    pm: "Paul Dimeglio",
    status: "open",
    phase: "construction",
    pendingSelections: 0,
    pastDueTasks: 9,
    dailyLogsRecentDone: 17,
    dailyLogsTotal: 164,
    foundationStarted: true,
    contractPrice: 953283.26,
    revenueToDate: 839240.47,
    wip: 114042.79000000004,
    estCloseDate: "2026-09-03",
    openedAt: "2025-07-15",
    slip: {"permit":0,"selections":0,"purchasing":0,"construction":0},
    notes: "164 daily logs · BT 153% complete · Site Work started (Construction) · Foundation started (daily logs required) · Last daily log 2026-08-20 · 164 daily logs",
  },
];

export const LIVE_JOBS: OwnerJob[] = OPEN_JOBS;

/** Sales funnel: Pipedrive Sales stages when PD cache present, else BT Lead Opportunities. */
export const LIVE_PIPELINE: PipelineStage[] = [
  {
    "id": "lead",
    "label": "Lead",
    "value": 36880628
  },
  {
    "id": "proposal",
    "label": "Proposal",
    "value": 2328721
  },
  {
    "id": "pre-contract",
    "label": "Pre-Contract",
    "value": 8641767
  },
  {
    "id": "contract",
    "label": "Contract",
    "value": 0
  },
  {
    "id": "closed",
    "label": "Closed / Won",
    "value": 60572032
  }
];

export const LIVE_SALES_PERFORMANCE: SalesPerformanceBar[] = [
  {
    "id": "backlog",
    "label": "Signed Backlog",
    "value": 7515280.41
  },
  {
    "id": "closings",
    "label": "Projected Closings",
    "value": 5873252.569999999
  },
  {
    "id": "signing",
    "label": "Expected Signing Value",
    "value": 0
  }
];

export const LIVE_TIME_METRICS: TimeMetric[] = [
  {
    "id": "contract-close",
    "label": "Contract to Close",
    "days": 420,
    "deltaDays": 0
  },
  {
    "id": "permit-close",
    "label": "Permit to Close",
    "days": 272,
    "deltaDays": 0
  },
  {
    "id": "slab-close",
    "label": "Slab Pour to Close",
    "days": 246,
    "deltaDays": 0
  }
];

export const LIVE_TARGET_MARGIN_PCT = 15;
export const LIVE_PROJECTED_MARGIN_PCT = 33.3;
export const LIVE_ROLLING_REVENUE_12MO = 16409316.15;
/** Weighted pipeline: Pipedrive value × stage probability when PD cache present. */
export const LIVE_WEIGHTED_PIPELINE = 10280650;
export const LIVE_SNAPSHOT_AT = '2026-08-24T16:29:18.117Z';
