/**
 * Ops-only Buildertrend import (all incomplete tasks + log aggregates).
 * Regenerated by `npm run buildertrend:update-snapshot` from data/buildertrend-cache.json.
 * Home dashboard continues to use LIVE_JOBS + LIVE_DRILLDOWN — this module is not imported there.
 */
import type { OpsBtImport } from './opsBtImportTypes';
import raw from './liveOpsImport.json';

export const LIVE_OPS_IMPORT = raw as OpsBtImport;

export function hasLiveOpsImport(): boolean {
  return Boolean(LIVE_OPS_IMPORT?.meta?.incompleteTaskCount);
}
