import { lazy,Suspense,useEffect,useState } from 'react';
import { Box,ChevronDown,Download,Grid2X2,Layers3,Move3D,PanelLeft,Save,Share2,Upload } from 'lucide-react';
import { FloorPlanEditor } from './components/editor2d/FloorPlanEditor'; import { Toolbar } from './components/ui/Toolbar'; import { usePlannerStore } from './store/plannerStore'; import { CatalogPanel } from './components/catalog/CatalogPanel';
import { roomArea,validatePlan } from './lib/geometry/rooms';
const Scene3D=lazy(()=>import('./components/scene3d/Scene3D').then(m=>({default:m.Scene3D})));
const finishes=[['Oak','#c9b18f'],['Walnut','#7d5c43'],['Stone','#a8aaa4'],['Ivory','#e9e2d2'],['Sage','#9aa697'],['Charcoal','#454b48']];
export default function App(){const store=usePlannerStore();const {walls,openings,furniture,selectedWallId,selectedFurnitureId,tool,view,cameraMode,floors,activeFloorId}=store;const [catalog,setCatalog]=useState(true);const selectedWall=walls.find(w=>w.id===selectedWallId),selectedFurniture=furniture.find(f=>f.id===selectedFurnitureId),validation=validatePlan(walls),area=validation.rooms.reduce((sum,r)=>sum+roomArea(r),0);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement)?.tagName;if(tag==='INPUT'||tag==='SELECT')return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?store.redo():store.undo()}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='d'){e.preventDefault();store.duplicateSelected()}else if(e.key==='Delete'||e.key==='Backspace')store.deleteSelected();else if(e.key==='Escape')store.setDraftStart(null);else if(e.key==='ArrowLeft')store.moveSelected(-.25,0);else if(e.key==='ArrowRight')store.moveSelected(.25,0);else if(e.key==='ArrowUp')store.moveSelected(0,-.25);else if(e.key==='ArrowDown')store.moveSelected(0,.25)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[store]);
 return <main className="app-shell"><header><div className="brand"><div className="logo"><Box size={21}/></div><div><strong>Roomcraft</strong><span>Spatial studio</span></div></div><button className="project-name">Lake House Study <ChevronDown size={15}/></button><div className="header-actions"><button onClick={store.load}><Upload size={16}/>Load</button><button onClick={store.exportProject}><Download size={16}/>Export</button><button><Share2 size={16}/>Share</button><button className="primary" onClick={store.save}><Save size={16}/>Save project</button><div className="avatar">BW</div></div></header>
 <nav><button className={view==='2d'?'active':''} onClick={()=>store.setView('2d')}><Grid2X2 size={17}/>Floor plan</button><button className={view==='3d'?'active':''} onClick={()=>store.setView('3d')}><Layers3 size={17}/>3D room</button><button className="catalog-toggle" onClick={()=>setCatalog(!catalog)}><PanelLeft size={16}/>{catalog?'Hide':'Show'} catalog</button></nav>
 <section className="workspace full"><aside className="left-panel"><p className="eyebrow">PROJECT</p><div className="floor-row"><select aria-label="Active floor" value={activeFloorId} onChange={e=>store.switchFloor(e.target.value)}>{floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button onClick={store.addFloor} title="Add floor">+</button></div><div className="card"><div><span>Walls</span><strong>{walls.length}</strong></div><div><span>Floor area</span><strong>{area.toFixed(1)} m²</strong></div><div><span>Openings</span><strong>{openings.length}</strong></div><div><span>Furniture</span><strong>{furniture.length}</strong></div></div>{!validation.valid&&walls.length>0&&<div className="plan-warning">Connect the highlighted endpoints to close the room.</div>}{view==='2d'?<><p className="eyebrow">DRAW</p><div className="hint"><Grid2X2 size={18}/><div><strong>{tool==='wall'?'Draw walls':tool==='door'||tool==='window'?`Place ${tool}`:'Select an object'}</strong><p>{tool==='wall'?'Click to start, then click each endpoint.':tool==='door'||tool==='window'?`Click a wall to add a ${tool}.`:'Click a wall to inspect it.'}</p></div></div></>:<><p className="eyebrow">CAMERA</p><div className="camera-modes">{(['top','orbit','walk'] as const).map(m=><button className={cameraMode===m?'active':''} onClick={()=>store.setCameraMode(m)} key={m}>{m}</button>)}</div><div className="hint scene-tip"><Move3D size={18}/><div><strong>Explore the room</strong><p>Orbit, zoom, or switch to eye-level walkthrough mode.</p></div></div></>}<div className="tip"><span>TIP</span>{view==='2d'?'Press Esc to finish a wall. Use Ctrl/Cmd+Z to undo.':'Drag an item from the catalog directly into the room.'}</div></aside>
 <section className="editor">{view==='2d'?<><Toolbar/><FloorPlanEditor/></>:<Suspense fallback={<div className="loading-3d">Preparing your room…</div>}><Scene3D/></Suspense>}</section>{catalog&&<CatalogPanel close={()=>setCatalog(false)}/>}<aside className="right-panel"><p className="eyebrow">PROPERTIES</p>{selectedWall?<WallProperties wall={selectedWall}/>:selectedFurniture?<FurnitureProperties item={selectedFurniture}/>:<FinishPanel/>}</aside></section>
 <footer><span className="status-dot"/>Project ready <span className="footer-spacer"/>Snap 25 cm · {walls.length} walls · {furniture.length} items</footer></main>}
function WallProperties({wall}:any){const openings=usePlannerStore(s=>s.openings.filter(o=>o.wallId===wall.id)),update=usePlannerStore(s=>s.updateOpening),remove=usePlannerStore(s=>s.deleteOpening);return <><h2>Wall</h2><Property label="Thickness" value={wall.thickness.toFixed(2)} unit="m"/><Property label="Height" value={wall.height.toFixed(2)} unit="m"/><Property label="Openings" value={String(openings.length)}/>{openings.map(o=><div className="opening-editor" key={o.id}><strong>{o.type}</strong><label>Position<input type="range" min=".05" max=".95" step=".05" value={o.offset} onChange={e=>update(o.id,{offset:+e.target.value})}/></label><label>Width<input type="number" min=".4" max="3" step=".1" value={o.width} onChange={e=>update(o.id,{width:+e.target.value})}/></label><button onClick={()=>remove(o.id)}>Remove</button></div>)}<p className="muted">Select the Door or Window tool, then click this wall to add an opening.</p></>}
function FurnitureProperties({item}:any){const update=usePlannerStore(s=>s.updateFurniture),move=usePlannerStore(s=>s.moveSelected),duplicate=usePlannerStore(s=>s.duplicateSelected);return <><h2>{item.name}</h2><Numeric label="Position X" value={item.x} onChange={x=>update(item.id,{x})}/><Numeric label="Position Z" value={item.z} onChange={z=>update(item.id,{z})}/><label>Rotation<input className="property-input" type="range" min="0" max="6.28" step="0.1" value={item.rotation} onChange={e=>update(item.id,{rotation:+e.target.value})}/></label><div className="nudge"><button onClick={()=>move(-.25,0)}>←</button><button onClick={()=>move(0,-.25)}>↑</button><button onClick={()=>move(0,.25)}>↓</button><button onClick={()=>move(.25,0)}>→</button></div><button className="duplicate" onClick={duplicate}>Duplicate item</button><label>Color<div className="swatches">{finishes.map(([name,color])=><button title={name} key={color} style={{background:color}} onClick={()=>update(item.id,{color})}/>)}</div></label></>}
function FinishPanel(){const set=usePlannerStore(s=>s.setFinish);return <><div className="empty-state"><div className="select-icon"><Grid2X2 size={25}/></div><h3>Room finishes</h3><p>Select a wall or furniture item for precise controls.</p></div><label>Floor material<div className="swatches">{finishes.map(([n,c])=><button title={n} key={c} style={{background:c}} onClick={()=>set('floor',c)}/>)}</div></label><label>Wall color<div className="swatches">{finishes.slice(3).map(([n,c])=><button title={n} key={c} style={{background:c}} onClick={()=>set('wall',c)}/>)}</div></label></>}
function Property({label,value,unit}:{label:string;value:string;unit?:string}){return <label>{label}<div className="input">{value}{unit&&<span>{unit}</span>}</div></label>}
function Numeric({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label>{label}<div className="number-input"><input type="number" step="0.25" value={value} onChange={e=>onChange(+e.target.value)}/><span>m</span></div></label>}
